In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/ecg-qwen-modality-expert
!pwd
!ls

/content/drive/MyDrive/ecg-qwen-modality-expert
/content/drive/MyDrive/ecg-qwen-modality-expert
data  README.md  results  summary

In [3]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")

(PROJECT_DIR / "notebooks").mkdir(exist_ok=True)
(PROJECT_DIR / "summary").mkdir(exist_ok=True)
(PROJECT_DIR / "results").mkdir(exist_ok=True)

print("Folders ready.")

Folders ready.

In [ ]:
!find /content/drive/MyDrive -name "03_ecg_qwen_agent_tools.ipynb"

/content/drive/MyDrive/Colab Notebooks/03_ecg_qwen_agent_tools.ipynb

In [ ]:
!pip install -q neurokit2 wfdb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 688.9/688.9 kB 51.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.9/163.9 kB 18.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 125.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
import os

BASE = Path("/content/drive/MyDrive")

print("MyDrive exists:", BASE.exists())

print("\nTop-level MyDrive folders/files:")
for item in list(BASE.iterdir())[:50]:
    print(item)

MyDrive exists: True

Top-level MyDrive folders/files:
/content/drive/MyDrive/Colab Notebooks
/content/drive/MyDrive/Colab
/content/drive/MyDrive/.ipynb_checkpoints
/content/drive/MyDrive/ecg-qwen-modality-expert

In [ ]:
csv_files = list(Path("/content/drive/MyDrive").rglob("*ecg*training*table*.csv"))

print("Found ECG training table CSV files:")
for f in csv_files:
    print(f)

Found ECG training table CSV files:
/content/drive/MyDrive/ecg-qwen-modality-expert/results/mini_ecg_qa_training_table.csv
/content/drive/MyDrive/ecg-qwen-modality-expert/results/mini_ecg_qa_training_table_with_images.csv
/content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_qa_training_table_1000_with_images.csv
/content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_qa_training_table_2500_with_images.csv

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
PTBXL_DIR = DATA_DIR / "ptbxl_mini"

candidate_paths = [
    RESULTS_DIR / "ecg_qa_training_table_2500_with_images.csv",
    RESULTS_DIR / "ecg_qa_training_table_1000_with_images.csv",
    RESULTS_DIR / "mini_ecg_qa_training_table_with_images.csv",
]

existing_candidates = [p for p in candidate_paths if p.exists()]

if len(existing_candidates) == 0:
    print("No standard candidate found. Searching MyDrive...")
    found = list(Path("/content/drive/MyDrive").rglob("*training_table*with_images*.csv"))
    for p in found:
        print(p)
    if len(found) == 0:
        raise FileNotFoundError("No training table with images found in MyDrive.")
    csv_path = found[0]
else:
    csv_path = existing_candidates[0]

print("Using CSV:", csv_path)

df_agent = pd.read_csv(csv_path)

print("Dataset shape:", df_agent.shape)
print("Columns:", df_agent.columns.tolist())
display(df_agent.head())

Using CSV: /content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_qa_training_table_2500_with_images.csv
Dataset shape: (2500, 7)
Columns: ['ecg_id', 'filename_lr', 'diagnostic_classes', 'diagnostic_class_main', 'question', 'answer', 'image_path']

,ecg_id,filename_lr,diagnostic_classes,diagnostic_class_main,question,answer,image_path
0,5726,records100/05000/05726_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
1,19957,records100/19000/19957_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
2,12451,records100/12000/12451_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
3,12707,records100/12000/12707_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
4,13364,records100/13000/13364_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...

In [ ]:
print("PTBXL_DIR:", PTBXL_DIR)
print("PTBXL_DIR exists:", PTBXL_DIR.exists())

if PTBXL_DIR.exists():
    print("Files in PTBXL_DIR:")
    for item in PTBXL_DIR.iterdir():
        print(item)

PTBXL_DIR: /content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini
PTBXL_DIR exists: True
Files in PTBXL_DIR:
/content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/scp_statements.csv
/content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/ptbxl_database.csv
/content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/records100

In [ ]:
example_row = df_agent.iloc[0]
record_path = PTBXL_DIR / example_row["filename_lr"]

print("Example record path:", record_path)
print("Exists .hea:", Path(str(record_path) + ".hea").exists())
print("Exists .dat:", Path(str(record_path) + ".dat").exists())

Example record path: /content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/records100/05000/05726_lr
Exists .hea: True
Exists .dat: True

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path
import wfdb

# Falls diese Pfade noch nicht gesetzt sind, erneut setzen
PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
PTBXL_DIR = DATA_DIR / "ptbxl_mini"

# Falls df_agent schon geladen ist, nutzen wir es.
# Sonst robust laden.
try:
    print("df_agent already loaded:", df_agent.shape)
except NameError:
    candidate_paths = [
        RESULTS_DIR / "ecg_qa_training_table_2500_with_images.csv",
        RESULTS_DIR / "ecg_qa_training_table_1000_with_images.csv",
        RESULTS_DIR / "mini_ecg_qa_training_table_with_images.csv",
    ]
    existing_candidates = [p for p in candidate_paths if p.exists()]
    if len(existing_candidates) == 0:
        found = list(Path("/content/drive/MyDrive").rglob("*training_table*with_images*.csv"))
        if len(found) == 0:
            raise FileNotFoundError("No ECG training table found.")
        csv_path = found[0]
    else:
        csv_path = existing_candidates[0]

    print("Using CSV:", csv_path)
    df_agent = pd.read_csv(csv_path)

print("Dataset shape:", df_agent.shape)
display(df_agent.head())

# Ein Beispiel auswählen
example_row = df_agent.iloc[0]
record_path = PTBXL_DIR / example_row["filename_lr"]

print("ECG ID:", example_row["ecg_id"])
print("Record path:", record_path)
print("Header exists:", Path(str(record_path) + ".hea").exists())
print("Data exists:", Path(str(record_path) + ".dat").exists())

signal, fields = wfdb.rdsamp(str(record_path))

print("Signal shape:", signal.shape)
print("Sampling frequency:", fields["fs"])
print("Lead names:", fields["sig_name"])

df_agent already loaded: (2500, 7)
Dataset shape: (2500, 7)

,ecg_id,filename_lr,diagnostic_classes,diagnostic_class_main,question,answer,image_path
0,5726,records100/05000/05726_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
1,19957,records100/19000/19957_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
2,12451,records100/12000/12451_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
3,12707,records100/12000/12707_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
4,13364,records100/13000/13364_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...

ECG ID: 5726
Record path: /content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/records100/05000/05726_lr
Header exists: True
Data exists: True
Signal shape: (1000, 12)
Sampling frequency: 100
Lead names: ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

In [ ]:
!pip install -q neurokit2

In [ ]:
import neurokit2 as nk
import numpy as np

def run_rhythm_feature_tool(record_path):
    signal, fields = wfdb.rdsamp(str(record_path))
    fs = int(fields["fs"])
    lead_names = fields["sig_name"]

    if "II" in lead_names:
        lead_idx = lead_names.index("II")
        lead_used = "II"
    else:
        lead_idx = 0
        lead_used = lead_names[0]

    ecg_lead = signal[:, lead_idx]

    try:
        signals, info = nk.ecg_process(ecg_lead, sampling_rate=fs)
        rpeaks = info.get("ECG_R_Peaks", [])

        if len(rpeaks) >= 2:
            rr_intervals_sec = np.diff(rpeaks) / fs
            mean_rr = float(np.mean(rr_intervals_sec))
            sd_rr = float(np.std(rr_intervals_sec))
            cv_rr = float(sd_rr / mean_rr) if mean_rr > 0 else np.nan
            estimated_hr = float(60 / mean_rr) if mean_rr > 0 else np.nan

            if cv_rr < 0.10:
                rhythm_regularity = "likely regular"
            elif cv_rr < 0.20:
                rhythm_regularity = "mildly irregular"
            else:
                rhythm_regularity = "irregular"
        else:
            mean_rr = np.nan
            sd_rr = np.nan
            cv_rr = np.nan
            estimated_hr = np.nan
            rhythm_regularity = "insufficient R-peaks detected"

        return {
            "tool_name": "NeuroKit2 rhythm feature tool",
            "lead_used": lead_used,
            "sampling_rate_hz": fs,
            "number_of_r_peaks": int(len(rpeaks)),
            "estimated_heart_rate_bpm": estimated_hr,
            "mean_rr_sec": mean_rr,
            "sd_rr_sec": sd_rr,
            "rr_coefficient_of_variation": cv_rr,
            "rhythm_regularity": rhythm_regularity,
            "interpretation_scope": "Rhythm feature assessment only; not a full arrhythmia diagnosis."
        }

    except Exception as e:
        return {
            "tool_name": "NeuroKit2 rhythm feature tool",
            "lead_used": lead_used,
            "sampling_rate_hz": fs,
            "error": str(e),
            "interpretation_scope": "Failed rhythm feature extraction."
        }

In [ ]:
!pip install -q huggingface_hub tensorflow keras

In [ ]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

import keras

ptbxl_model = keras.saving.load_model("hf://Steenslid/ecg-ptbxl-classification")

print("Loaded pretrained PTB-XL classifier.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--Steenslid--ecg-ptbxl-classification/snapshots/ce86c40244a8f9df95b2274ccc1ed1ccfc2c13a6/config.json'

In [ ]:
!pip install -q huggingface_hub tensorflow keras

In [ ]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

from huggingface_hub import hf_hub_download
import keras
import numpy as np
import json

repo_id = "Steenslid/ecg-ptbxl-classification"

model_path = hf_hub_download(
    repo_id=repo_id,
    filename="ecg_model.keras"
)

norm_path = hf_hub_download(
    repo_id=repo_id,
    filename="normalisation_params.npz"
)

thresholds_path = hf_hub_download(
    repo_id=repo_id,
    filename="thresholds.json"
)

print("Model path:", model_path)
print("Normalisation path:", norm_path)
print("Thresholds path:", thresholds_path)

ptbxl_model = keras.saving.load_model(model_path)

normalisation_params = np.load(norm_path)

with open(thresholds_path, "r") as f:
    thresholds = json.load(f)

print("Loaded pretrained PTB-XL classifier.")
print("Model input shape:", ptbxl_model.input_shape)
print("Model output shape:", ptbxl_model.output_shape)
print("Normalisation keys:", normalisation_params.files)
print("Thresholds:", thresholds)

Model path: /root/.cache/huggingface/hub/models--Steenslid--ecg-ptbxl-classification/snapshots/ce86c40244a8f9df95b2274ccc1ed1ccfc2c13a6/ecg_model.keras
Normalisation path: /root/.cache/huggingface/hub/models--Steenslid--ecg-ptbxl-classification/snapshots/ce86c40244a8f9df95b2274ccc1ed1ccfc2c13a6/normalisation_params.npz
Thresholds path: /root/.cache/huggingface/hub/models--Steenslid--ecg-ptbxl-classification/snapshots/ce86c40244a8f9df95b2274ccc1ed1ccfc2c13a6/thresholds.json
Loaded pretrained PTB-XL classifier.
Model input shape: (None, 1000, 12)
Model output shape: (None, 5)
Normalisation keys: ['mean', 'std']
Thresholds: {'NORM': 0.44000000000000006, 'MI': 0.35000000000000003, 'STTC': 0.33, 'CD': 0.26000000000000006, 'HYP': 0.2}

In [ ]:
for key in normalisation_params.files:
    arr = normalisation_params[key]
    print(key, arr.shape, arr[:5] if arr.ndim > 0 else arr)

mean (1, 1, 12) [[[-0.00175328 -0.00153416  0.00021845  0.00162679 -0.00093135
   -0.00063464  0.00017061 -0.00096292 -0.00158111 -0.00136748
   -0.00080109 -0.00244466]]]
std (1, 1, 12) [[[0.15558097 0.15519816 0.15516405 0.13463277 0.13483134 0.13428216
   0.22876117 0.32718202 0.32123756 0.28591523 0.2656472  0.27578676]]]

In [ ]:
def normalize_ecg_signal(x, normalisation_params):
    """
    x shape: 1000 x 12
    """
    keys = normalisation_params.files

    if "mean" in keys and "std" in keys:
        mean = normalisation_params["mean"]
        std = normalisation_params["std"]
        return (x - mean) / (std + 1e-8)

    elif "means" in keys and "stds" in keys:
        mean = normalisation_params["means"]
        std = normalisation_params["stds"]
        return (x - mean) / (std + 1e-8)

    elif "mu" in keys and "sigma" in keys:
        mean = normalisation_params["mu"]
        std = normalisation_params["sigma"]
        return (x - mean) / (std + 1e-8)

    else:
        print("Warning: Unknown normalisation keys. Returning unnormalized signal.")
        return x


def run_ptbxl_classifier_tool(record_path):
    signal, fields = wfdb.rdsamp(str(record_path))

    x = signal.astype("float32")

    # Erwartet: 1000 x 12
    if x.shape[0] != 1000:
        if x.shape[0] > 1000:
            x = x[:1000, :]
        else:
            pad_len = 1000 - x.shape[0]
            x = np.pad(x, ((0, pad_len), (0, 0)), mode="constant")

    x = normalize_ecg_signal(x, normalisation_params)

    x_batch = np.expand_dims(x, axis=0)

    y_pred = ptbxl_model.predict(x_batch, verbose=0)

    if isinstance(y_pred, list):
        y_pred = y_pred[0]

    probs = np.array(y_pred).reshape(-1)

    labels = ["NORM", "MI", "STTC", "CD", "HYP"]

    # thresholds.json kann entweder Liste oder Dict sein
    if isinstance(thresholds, dict):
        predicted_labels = [
            label for label, prob in zip(labels, probs)
            if prob >= float(thresholds.get(label, 0.5))
        ]
    else:
        predicted_labels = [
            label for label, prob, thr in zip(labels, probs, thresholds)
            if prob >= float(thr)
        ]

    if len(predicted_labels) == 0:
        predicted_labels = [labels[int(np.argmax(probs))]]

    return {
        "tool_name": "pretrained PTB-XL classifier",
        "classes": labels,
        "probabilities": {label: float(prob) for label, prob in zip(labels, probs)},
        "predicted_labels": predicted_labels,
        "top_class": labels[int(np.argmax(probs))],
        "interpretation_scope": "Pretrained signal-based PTB-XL superclass classifier."
    }

In [ ]:
def normalize_ecg_signal(x, normalisation_params):
    """
    x shape expected: 1000 x 12
    Returns shape: 1000 x 12
    """
    keys = normalisation_params.files

    if "mean" in keys and "std" in keys:
        mean = normalisation_params["mean"]
        std = normalisation_params["std"]
    elif "means" in keys and "stds" in keys:
        mean = normalisation_params["means"]
        std = normalisation_params["stds"]
    elif "mu" in keys and "sigma" in keys:
        mean = normalisation_params["mu"]
        std = normalisation_params["sigma"]
    else:
        print("Warning: Unknown normalisation keys. Returning unnormalized signal.")
        return x

    # Entferne unnötige Batch-Dimensionen, falls vorhanden
    mean = np.squeeze(mean)
    std = np.squeeze(std)

    # Falls mean/std pro Lead vorliegen, z.B. shape (12,)
    # oder vollständig pro Sample/Lead, z.B. shape (1000, 12), funktioniert Broadcasting.
    x_norm = (x - mean) / (std + 1e-8)

    # Sicherstellen, dass Ergebnis wieder 1000 x 12 ist
    x_norm = np.squeeze(x_norm)

    if x_norm.shape != (1000, 12):
        print("Warning: normalized signal has unexpected shape:", x_norm.shape)

    return x_norm.astype("float32")


def run_ptbxl_classifier_tool(record_path):
    signal, fields = wfdb.rdsamp(str(record_path))

    x = signal.astype("float32")

    # Erwartet: 1000 x 12
    if x.shape[0] != 1000:
        if x.shape[0] > 1000:
            x = x[:1000, :]
        else:
            pad_len = 1000 - x.shape[0]
            x = np.pad(x, ((0, pad_len), (0, 0)), mode="constant")

    # Falls mehr als 12 Kanäle oder weniger, prüfen
    if x.shape[1] != 12:
        raise ValueError(f"Expected 12 leads, but got shape {x.shape}")

    print("Raw signal shape:", x.shape)

    x = normalize_ecg_signal(x, normalisation_params)

    print("Normalized signal shape:", x.shape)

    # Modell erwartet Batch x 1000 x 12
    x_batch = np.expand_dims(x, axis=0)

    print("Model input shape:", x_batch.shape)

    y_pred = ptbxl_model.predict(x_batch, verbose=0)

    if isinstance(y_pred, list):
        y_pred = y_pred[0]

    probs = np.array(y_pred).reshape(-1)

    labels = ["NORM", "MI", "STTC", "CD", "HYP"]

    # thresholds.json kann entweder Liste oder Dict sein
    if isinstance(thresholds, dict):
        predicted_labels = [
            label for label, prob in zip(labels, probs)
            if prob >= float(thresholds.get(label, 0.5))
        ]
    else:
        predicted_labels = [
            label for label, prob, thr in zip(labels, probs, thresholds)
            if prob >= float(thr)
        ]

    if len(predicted_labels) == 0:
        predicted_labels = [labels[int(np.argmax(probs))]]

    return {
        "tool_name": "pretrained PTB-XL classifier",
        "classes": labels,
        "probabilities": {label: float(prob) for label, prob in zip(labels, probs)},
        "predicted_labels": predicted_labels,
        "top_class": labels[int(np.argmax(probs))],
        "interpretation_scope": "Pretrained signal-based PTB-XL superclass classifier."
    }

In [ ]:
ptbxl_output = run_ptbxl_classifier_tool(record_path)
ptbxl_output

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

{'tool_name': 'pretrained PTB-XL classifier',
 'classes': ['NORM', 'MI', 'STTC', 'CD', 'HYP'],
 'probabilities': {'NORM': 0.9920564293861389,
  'MI': 0.0007271073991432786,
  'STTC': 0.001419559819623828,
  'CD': 0.003178607439622283,
  'HYP': 0.00048198708100244403},
 'predicted_labels': ['NORM'],
 'top_class': 'NORM',
 'interpretation_scope': 'Pretrained signal-based PTB-XL superclass classifier.'}

In [ ]:
rhythm_output = run_rhythm_feature_tool(record_path)
ptbxl_output = run_ptbxl_classifier_tool(record_path)

print("Rhythm tool output:")
print(rhythm_output)

print("\nPTB-XL classifier output:")
print(ptbxl_output)

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Rhythm tool output:
{'tool_name': 'NeuroKit2 rhythm feature tool', 'lead_used': 'II', 'sampling_rate_hz': 100, 'number_of_r_peaks': 11, 'estimated_heart_rate_bpm': 65.86169045005488, 'mean_rr_sec': 0.9110000000000001, 'sd_rr_sec': 0.01640121946685674, 'rr_coefficient_of_variation': 0.018003533992158878, 'rhythm_regularity': 'likely regular', 'interpretation_scope': 'Rhythm feature assessment only; not a full arrhythmia diagnosis.'}

PTB-XL classifier output:
{'tool_name': 'pretrained PTB-XL classifier', 'classes': ['NORM', 'MI', 'STTC', 'CD', 'HYP'], 'probabilities': {'NORM': 0.9920564293861389, 'MI': 0.0007271073991432786, 'STTC': 0.001419559819623828, 'CD': 0.003178607439622283, 'HYP': 0.00048198708100244403}, 'predicted_labels': ['NORM'], 'top_class': 'NORM', 'interpretation_scope': 'Pretrained signal-based PTB-XL superclass classifier.'}

In [ ]:
LABEL_MEANINGS = {
    "NORM": "normal ECG",
    "MI": "myocardial infarction",
    "STTC": "ST/T changes",
    "CD": "conduction disturbance",
    "HYP": "hypertrophy"
}

def create_agent_summary_from_tools(rhythm_output, ptbxl_output):
    probs = ptbxl_output["probabilities"]
    sorted_probs = sorted(probs.items(), key=lambda x: x[1], reverse=True)

    predicted_labels = ptbxl_output.get("predicted_labels", [])
    top_label, top_prob = sorted_probs[0]
    top_meaning = LABEL_MEANINGS.get(top_label, top_label)

    lines = []
    lines.append("ECG Agent Summary")
    lines.append("")
    lines.append("1. Rhythm assessment")
    lines.append(f"- Lead used: {rhythm_output.get('lead_used', 'unknown')}")
    lines.append(f"- Number of detected R-peaks: {rhythm_output.get('number_of_r_peaks', 'unknown')}")

    hr = rhythm_output.get("estimated_heart_rate_bpm", None)
    if isinstance(hr, (int, float)) and not np.isnan(hr):
        lines.append(f"- Estimated heart rate: {hr:.1f} bpm")
    else:
        lines.append("- Estimated heart rate: unavailable")

    lines.append(f"- Rhythm regularity: {rhythm_output.get('rhythm_regularity', 'unknown')}")
    lines.append("- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.")
    lines.append("")
    lines.append("2. Diagnostic superclass classification")
    lines.append(f"- Predicted label(s) above threshold: {', '.join(predicted_labels)}")
    lines.append(f"- Highest probability class: {top_label} ({top_meaning}), probability {top_prob:.3f}")
    lines.append("")
    lines.append("Class probabilities:")
    for label, prob in sorted_probs:
        meaning = LABEL_MEANINGS.get(label, label)
        lines.append(f"- {label} ({meaning}): {prob:.3f}")

    lines.append("")
    lines.append("3. Integrated interpretation")

    if "NORM" in predicted_labels and len(predicted_labels) == 1:
        lines.append("- The pretrained signal classifier primarily suggests a normal ECG pattern.")
    elif len(predicted_labels) > 0:
        expanded = [f"{label} ({LABEL_MEANINGS.get(label, label)})" for label in predicted_labels]
        lines.append(
            f"- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): {', '.join(expanded)}."
        )
    else:
        lines.append(
            f"- No class exceeded the predefined threshold; the highest probability class was {top_label} ({top_meaning})."
        )

    lines.append("- The rhythm feature tool provides supportive rhythm information based on R-peak detection.")
    lines.append("- This is a research prototype and not a clinical diagnosis.")

    return "\n".join(lines)

In [ ]:
agent_summary = create_agent_summary_from_tools(rhythm_output, ptbxl_output)
print(agent_summary)

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 65.9 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.992

Class probabilities:
- NORM (normal ECG): 0.992
- CD (conduction disturbance): 0.003
- STTC (ST/T changes): 0.001
- MI (myocardial infarction): 0.001
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
def run_ecg_agent(row=None, record_id=None):
    if row is None:
        if record_id is None:
            raise ValueError("Please provide either row or record_id.")
        row = df_agent[df_agent["ecg_id"].astype(int) == int(record_id)].iloc[0]

    record_path = PTBXL_DIR / row["filename_lr"]

    rhythm_output = run_rhythm_feature_tool(record_path)
    ptbxl_output = run_ptbxl_classifier_tool(record_path)
    agent_summary = create_agent_summary_from_tools(rhythm_output, ptbxl_output)

    return {
        "ecg_id": int(row["ecg_id"]),
        "record_path": str(record_path),
        "true_diagnostic_class_main": row.get("diagnostic_class_main", None),
        "true_diagnostic_classes": row.get("diagnostic_classes", None),
        "rhythm_tool_output": rhythm_output,
        "ptbxl_classifier_output": ptbxl_output,
        "agent_summary": agent_summary
    }

In [ ]:
agent_result = run_ecg_agent(row=example_row)

print("ECG ID:", agent_result["ecg_id"])
print("True main class:", agent_result["true_diagnostic_class_main"])
print("True diagnostic classes:", agent_result["true_diagnostic_classes"])

print("\nAgent summary:\n")
print(agent_result["agent_summary"])

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
ECG ID: 5726
True main class: NORM
True diagnostic classes: ['NORM']

Agent summary:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 65.9 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.992

Class probabilities:
- NORM (normal ECG): 0.992
- CD (conduction disturbance): 0.003
- STTC (ST/T changes): 0.001
- MI (myocardial infarction): 0.001
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
agent_results = []

for i in range(5):
    row = df_agent.iloc[i]
    result = run_ecg_agent(row=row)
    agent_results.append(result)

    print("=" * 80)
    print("ECG ID:", result["ecg_id"])
    print("True main class:", result["true_diagnostic_class_main"])
    print(result["agent_summary"])

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
================================================================================
ECG ID: 5726
True main class: NORM
ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 65.9 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.992

Class probabilities:
- NORM (normal ECG): 0.992
- CD (conduction disturbance): 0.003
- STTC (ST/T changes): 0.001
- MI (myocardial infarction): 0.001
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
================================================================================
ECG ID: 19957
True main class: NORM
ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 68.0 bpm
- Rhythm regularity: irregular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.944

Class probabilities:
- NORM (normal ECG): 0.944
- CD (conduction disturbance): 0.030
- MI (myocardial infarction): 0.011
- STTC (ST/T changes): 0.011
- HYP (hypertrophy): 0.003

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
================================================================================
ECG ID: 12451
True main class: NORM
ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 10
- Estimated heart rate: 62.8 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.974

Class probabilities:
- NORM (normal ECG): 0.974
- STTC (ST/T changes): 0.010
- MI (myocardial infarction): 0.007
- CD (conduction disturbance): 0.002
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
================================================================================
ECG ID: 12707
True main class: NORM
ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 8
- Estimated heart rate: 49.8 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM, HYP
- Highest probability class: HYP (hypertrophy), probability 0.640

Class probabilities:
- HYP (hypertrophy): 0.640
- NORM (normal ECG): 0.530
- STTC (ST/T changes): 0.013
- CD (conduction disturbance): 0.005
- MI (myocardial infarction): 0.004

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): NORM (normal ECG), HYP (hypertrophy).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
================================================================================
ECG ID: 13364
True main class: NORM
ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 9
- Estimated heart rate: 58.7 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.947

Class probabilities:
- NORM (normal ECG): 0.947
- MI (myocardial infarction): 0.028
- CD (conduction disturbance): 0.024
- STTC (ST/T changes): 0.005
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
import json
import pandas as pd

rows = []

for result in agent_results:
    probs = result["ptbxl_classifier_output"]["probabilities"]

    rows.append({
        "ecg_id": result["ecg_id"],
        "true_diagnostic_class_main": result["true_diagnostic_class_main"],
        "true_diagnostic_classes": result["true_diagnostic_classes"],
        "heart_rate_bpm": result["rhythm_tool_output"].get("estimated_heart_rate_bpm", None),
        "rhythm_regularity": result["rhythm_tool_output"].get("rhythm_regularity", None),
        "number_of_r_peaks": result["rhythm_tool_output"].get("number_of_r_peaks", None),
        "predicted_labels": ", ".join(result["ptbxl_classifier_output"].get("predicted_labels", [])),
        "top_class": result["ptbxl_classifier_output"].get("top_class", None),
        "prob_NORM": probs.get("NORM", None),
        "prob_MI": probs.get("MI", None),
        "prob_STTC": probs.get("STTC", None),
        "prob_CD": probs.get("CD", None),
        "prob_HYP": probs.get("HYP", None),
        "agent_summary": result["agent_summary"]
    })

agent_outputs_df = pd.DataFrame(rows)

agent_outputs_path = RESULTS_DIR / "ecg_agent_tool_outputs_demo.csv"
agent_outputs_df.to_csv(agent_outputs_path, index=False)

display(agent_outputs_df)
print("Saved agent tool outputs to:", agent_outputs_path)

,ecg_id,true_diagnostic_class_main,true_diagnostic_classes,heart_rate_bpm,rhythm_regularity,number_of_r_peaks,predicted_labels,top_class,prob_NORM,prob_MI,prob_STTC,prob_CD,prob_HYP,agent_summary
0,5726,NORM,['NORM'],65.861690,likely regular,11,NORM,NORM,0.992056,0.000727,0.001420,0.003179,0.000482,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
1,19957,NORM,['NORM'],67.950170,irregular,11,NORM,NORM,0.944263,0.011218,0.011116,0.029648,0.003430,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
2,12451,NORM,['NORM'],62.790698,likely regular,10,NORM,NORM,0.974085,0.006688,0.010100,0.001923,0.000437,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
3,12707,NORM,['NORM'],49.763033,likely regular,8,"NORM, HYP",HYP,0.530302,0.003572,0.012525,0.005492,0.640136,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
4,13364,NORM,['NORM'],58.679707,likely regular,9,NORM,NORM,0.946550,0.027738,0.005418,0.023868,0.000333,ECG Agent Summary\n\n1. Rhythm assessment\n- L...

Saved agent tool outputs to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_agent_tool_outputs_demo.csv

In [ ]:
from tqdm import tqdm
import pandas as pd
import numpy as np
import json
from pathlib import Path

N_AGENT_EXAMPLES = min(1000, len(df_agent))

agent_training_results = []
failed_agent_examples = []

for i in tqdm(range(N_AGENT_EXAMPLES)):
    row = df_agent.iloc[i]

    try:
        result = run_ecg_agent(row=row)
        agent_training_results.append(result)
    except Exception as e:
        failed_agent_examples.append({
            "index": i,
            "ecg_id": row.get("ecg_id", "unknown"),
            "error": str(e)
        })
        print("Failed ECG ID:", row.get("ecg_id", "unknown"), "Error:", e)

print("Created agent examples:", len(agent_training_results))
print("Failed examples:", len(failed_agent_examples))

if len(failed_agent_examples) > 0:
    print("First failed examples:")
    print(failed_agent_examples[:5])

  0%|          | 1/1000 [00:00<09:19,  1.78it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  0%|          | 3/1000 [00:01<09:44,  1.70it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  0%|          | 4/1000 [00:02<07:42,  2.16it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  0%|          | 5/1000 [00:02<07:13,  2.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 6/1000 [00:03<11:36,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 8/1000 [00:06<16:18,  1.01it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 9/1000 [00:07<15:40,  1.05it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 10/1000 [00:07<15:01,  1.10it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 11/1000 [00:08<15:35,  1.06it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|          | 12/1000 [00:09<15:12,  1.08it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|▏         | 13/1000 [00:10<14:35,  1.13it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  1%|▏         | 14/1000 [00:11<14:40,  1.12it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 15/1000 [00:12<14:28,  1.13it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 16/1000 [00:13<13:36,  1.20it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 17/1000 [00:13<12:18,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 18/1000 [00:14<12:06,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 19/1000 [00:14<11:21,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 20/1000 [00:15<10:58,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 21/1000 [00:16<11:26,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 22/1000 [00:17<11:38,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 23/1000 [00:17<12:03,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▏         | 24/1000 [00:18<12:36,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  2%|▎         | 25/1000 [00:19<12:52,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 26/1000 [00:20<11:47,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 27/1000 [00:20<12:00,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 28/1000 [00:22<14:01,  1.16it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 29/1000 [00:22<12:36,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 30/1000 [00:23<11:56,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 31/1000 [00:23<11:20,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 32/1000 [00:24<11:21,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 33/1000 [00:25<11:10,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  3%|▎         | 34/1000 [00:25<10:52,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▎         | 35/1000 [00:26<12:10,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▎         | 36/1000 [00:27<12:08,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▎         | 37/1000 [00:28<11:29,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 38/1000 [00:28<11:32,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 39/1000 [00:29<11:20,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 40/1000 [00:30<10:47,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 41/1000 [00:31<11:08,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 42/1000 [00:31<11:03,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 43/1000 [00:32<11:04,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 44/1000 [00:33<11:15,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  4%|▍         | 45/1000 [00:33<10:47,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▍         | 46/1000 [00:34<10:11,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▍         | 47/1000 [00:35<11:02,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▍         | 48/1000 [00:35<11:28,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▍         | 49/1000 [00:36<10:29,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▌         | 50/1000 [00:37<10:24,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▌         | 51/1000 [00:37<10:33,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▌         | 52/1000 [00:38<11:45,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▌         | 53/1000 [00:39<11:15,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  5%|▌         | 54/1000 [00:39<10:42,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 55/1000 [00:40<10:35,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 56/1000 [00:41<11:19,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 57/1000 [00:42<11:11,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 58/1000 [00:43<12:06,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 59/1000 [00:43<11:38,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 60/1000 [00:44<12:34,  1.25it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 61/1000 [00:45<11:23,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▌         | 62/1000 [00:45<11:41,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▋         | 63/1000 [00:46<11:46,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▋         | 64/1000 [00:47<12:16,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  6%|▋         | 65/1000 [00:48<12:34,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 66/1000 [00:49<12:04,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 67/1000 [00:49<12:16,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 68/1000 [00:50<13:12,  1.18it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 69/1000 [00:51<12:27,  1.25it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 70/1000 [00:52<12:13,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 71/1000 [00:53<11:50,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 72/1000 [00:53<11:39,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 73/1000 [00:54<12:29,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  7%|▋         | 74/1000 [00:55<11:10,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 75/1000 [00:56<11:53,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 76/1000 [00:56<11:31,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 77/1000 [00:57<10:59,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 78/1000 [00:58<10:14,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 79/1000 [00:58<10:27,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 80/1000 [00:59<11:07,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 81/1000 [01:00<11:17,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 82/1000 [01:01<11:14,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 83/1000 [01:01<11:05,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 84/1000 [01:02<11:51,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  8%|▊         | 85/1000 [01:03<10:57,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▊         | 86/1000 [01:04<11:30,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▊         | 87/1000 [01:04<11:53,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 88/1000 [01:05<10:40,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 89/1000 [01:06<10:29,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 90/1000 [01:06<10:06,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 91/1000 [01:07<09:15,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 92/1000 [01:07<09:19,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 93/1000 [01:08<08:40,  1.74it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

  9%|▉         | 94/1000 [01:09<09:37,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|▉         | 95/1000 [01:09<10:21,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|▉         | 96/1000 [01:10<10:00,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|▉         | 97/1000 [01:11<10:55,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|▉         | 98/1000 [01:11<10:01,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|▉         | 99/1000 [01:12<09:40,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 100/1000 [01:13<10:33,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 101/1000 [01:14<10:22,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 102/1000 [01:14<10:28,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 103/1000 [01:15<10:11,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 104/1000 [01:16<09:55,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 10%|█         | 105/1000 [01:16<09:31,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 106/1000 [01:17<10:41,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 107/1000 [01:18<10:17,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 108/1000 [01:18<10:36,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 109/1000 [01:19<10:50,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 110/1000 [01:20<10:28,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 111/1000 [01:20<10:13,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█         | 112/1000 [01:21<10:38,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█▏        | 113/1000 [01:22<10:17,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 11%|█▏        | 114/1000 [01:23<10:31,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 115/1000 [01:23<09:46,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 116/1000 [01:24<09:31,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 117/1000 [01:24<09:22,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 118/1000 [01:25<09:33,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 119/1000 [01:26<09:52,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 120/1000 [01:27<10:04,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 121/1000 [01:27<10:10,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 122/1000 [01:28<09:34,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 123/1000 [01:28<09:30,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▏        | 124/1000 [01:29<08:52,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 12%|█▎        | 125/1000 [01:30<09:57,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 126/1000 [01:30<09:09,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 127/1000 [01:31<08:46,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 128/1000 [01:32<09:08,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 129/1000 [01:32<08:40,  1.67it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 130/1000 [01:33<09:41,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 131/1000 [01:34<09:43,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 132/1000 [01:34<09:26,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 133/1000 [01:35<11:04,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 13%|█▎        | 134/1000 [01:36<11:37,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▎        | 135/1000 [01:37<11:02,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▎        | 136/1000 [01:38<11:14,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▎        | 137/1000 [01:38<10:39,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 138/1000 [01:39<10:52,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 139/1000 [01:40<10:32,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 140/1000 [01:40<10:04,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 141/1000 [01:41<09:28,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 142/1000 [01:42<09:18,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 143/1000 [01:42<09:20,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 144/1000 [01:43<09:09,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 14%|█▍        | 145/1000 [01:44<10:06,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▍        | 146/1000 [01:44<09:26,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▍        | 147/1000 [01:45<08:58,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▍        | 148/1000 [01:45<08:42,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▍        | 149/1000 [01:46<10:01,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▌        | 150/1000 [01:47<10:53,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▌        | 151/1000 [01:48<10:46,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▌        | 152/1000 [01:49<10:45,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▌        | 153/1000 [01:49<09:44,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 15%|█▌        | 154/1000 [01:50<09:19,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 155/1000 [01:51<09:33,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 156/1000 [01:51<09:40,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 157/1000 [01:52<09:48,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 158/1000 [01:53<10:21,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 159/1000 [01:54<10:08,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 160/1000 [01:54<09:20,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 161/1000 [01:55<08:58,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▌        | 162/1000 [01:55<08:36,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▋        | 163/1000 [01:56<08:36,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▋        | 164/1000 [01:57<09:36,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 16%|█▋        | 165/1000 [01:57<09:44,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 166/1000 [01:58<10:25,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 167/1000 [01:59<10:00,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 168/1000 [02:00<09:45,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 169/1000 [02:00<09:10,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 170/1000 [02:01<08:42,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 171/1000 [02:01<08:15,  1.67it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 172/1000 [02:02<08:30,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 173/1000 [02:03<08:23,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 17%|█▋        | 174/1000 [02:03<08:27,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 175/1000 [02:04<08:03,  1.71it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 176/1000 [02:04<08:49,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 177/1000 [02:05<08:46,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 178/1000 [02:06<08:37,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 179/1000 [02:06<08:39,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 180/1000 [02:07<08:46,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 181/1000 [02:08<08:57,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 182/1000 [02:08<09:39,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 183/1000 [02:09<08:38,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 184/1000 [02:10<09:17,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 18%|█▊        | 185/1000 [02:10<09:25,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▊        | 186/1000 [02:11<09:45,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▊        | 187/1000 [02:12<09:01,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 188/1000 [02:12<08:40,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 189/1000 [02:13<08:26,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 190/1000 [02:14<09:18,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 191/1000 [02:14<08:44,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 192/1000 [02:15<08:46,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 193/1000 [02:16<08:21,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 19%|█▉        | 194/1000 [02:16<08:15,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|█▉        | 195/1000 [02:17<08:45,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|█▉        | 196/1000 [02:18<08:51,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|█▉        | 197/1000 [02:18<08:50,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|█▉        | 198/1000 [02:19<09:42,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|█▉        | 199/1000 [02:20<09:16,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 200/1000 [02:20<09:23,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 201/1000 [02:21<09:48,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 202/1000 [02:22<09:43,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 203/1000 [02:23<09:14,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 204/1000 [02:23<08:43,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 20%|██        | 205/1000 [02:24<08:46,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 206/1000 [02:25<08:57,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 207/1000 [02:25<08:27,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 208/1000 [02:26<09:00,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 209/1000 [02:27<08:48,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 210/1000 [02:27<08:52,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 211/1000 [02:28<09:11,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██        | 212/1000 [02:29<08:49,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██▏       | 213/1000 [02:29<08:34,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 21%|██▏       | 214/1000 [02:30<08:28,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 215/1000 [02:30<08:19,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 216/1000 [02:31<08:11,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 217/1000 [02:32<08:20,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 218/1000 [02:32<08:16,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 219/1000 [02:33<08:39,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 220/1000 [02:34<08:28,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 221/1000 [02:34<08:54,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 222/1000 [02:35<08:47,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 223/1000 [02:36<09:08,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▏       | 224/1000 [02:36<08:42,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 22%|██▎       | 225/1000 [02:38<09:58,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 226/1000 [02:38<09:21,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 227/1000 [02:39<09:07,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 228/1000 [02:39<08:33,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 229/1000 [02:40<08:26,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 230/1000 [02:41<08:20,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 231/1000 [02:41<08:04,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 232/1000 [02:42<08:12,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 233/1000 [02:43<08:42,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 23%|██▎       | 234/1000 [02:43<08:08,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▎       | 235/1000 [02:44<08:03,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▎       | 236/1000 [02:45<08:31,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▎       | 237/1000 [02:45<08:39,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 238/1000 [02:46<08:27,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 239/1000 [02:47<08:19,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 240/1000 [02:47<08:22,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 241/1000 [02:48<08:40,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 242/1000 [02:49<08:16,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 243/1000 [02:49<08:20,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 244/1000 [02:50<08:41,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 24%|██▍       | 245/1000 [02:50<08:02,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▍       | 246/1000 [02:51<08:02,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▍       | 247/1000 [02:52<08:18,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▍       | 248/1000 [02:52<07:57,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▍       | 249/1000 [02:53<08:34,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▌       | 250/1000 [02:54<08:12,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▌       | 251/1000 [02:54<07:56,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▌       | 252/1000 [02:55<08:23,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▌       | 253/1000 [02:56<09:26,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 25%|██▌       | 254/1000 [02:57<09:46,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 255/1000 [02:58<09:30,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 256/1000 [02:58<09:40,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 257/1000 [02:59<09:22,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 258/1000 [03:00<09:29,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 259/1000 [03:01<08:49,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 260/1000 [03:01<08:30,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 261/1000 [03:02<08:34,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▌       | 262/1000 [03:03<08:30,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▋       | 263/1000 [03:04<09:19,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▋       | 264/1000 [03:04<08:48,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 26%|██▋       | 265/1000 [03:05<09:00,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 267/1000 [03:06<08:57,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 268/1000 [03:07<09:50,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 269/1000 [03:08<09:21,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 270/1000 [03:09<09:11,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 271/1000 [03:10<09:19,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 272/1000 [03:10<08:43,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 273/1000 [03:11<08:37,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 27%|██▋       | 274/1000 [03:12<08:17,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 275/1000 [03:12<07:58,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 276/1000 [03:13<07:34,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 277/1000 [03:13<07:03,  1.71it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 278/1000 [03:14<07:26,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 279/1000 [03:14<07:26,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 280/1000 [03:15<07:29,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 281/1000 [03:16<08:06,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 282/1000 [03:16<07:36,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 283/1000 [03:17<08:06,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 284/1000 [03:18<08:02,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 28%|██▊       | 285/1000 [03:19<08:00,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▊       | 286/1000 [03:19<08:34,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▊       | 287/1000 [03:20<08:52,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 288/1000 [03:21<08:57,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 289/1000 [03:22<09:01,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 290/1000 [03:22<08:11,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 291/1000 [03:23<07:51,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 292/1000 [03:24<08:08,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 293/1000 [03:24<07:54,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 29%|██▉       | 294/1000 [03:25<07:44,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|██▉       | 295/1000 [03:26<07:59,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|██▉       | 296/1000 [03:26<07:58,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|██▉       | 297/1000 [03:27<07:31,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|██▉       | 298/1000 [03:28<07:47,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|██▉       | 299/1000 [03:28<08:01,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|███       | 300/1000 [03:29<09:04,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|███       | 301/1000 [03:31<10:39,  1.09it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|███       | 302/1000 [03:32<10:45,  1.08it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|███       | 304/1000 [03:34<11:54,  1.03s/it]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 30%|███       | 305/1000 [03:35<11:16,  1.03it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 306/1000 [03:35<10:05,  1.15it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 307/1000 [03:36<10:45,  1.07it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 308/1000 [03:37<10:25,  1.11it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 309/1000 [03:38<10:37,  1.08it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 310/1000 [03:39<10:40,  1.08it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 311/1000 [03:40<10:08,  1.13it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███       | 312/1000 [03:41<10:54,  1.05it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███▏      | 313/1000 [03:42<10:48,  1.06it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 31%|███▏      | 314/1000 [03:43<09:34,  1.19it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 315/1000 [03:43<08:51,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 316/1000 [03:44<08:32,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 317/1000 [03:45<08:35,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 318/1000 [03:45<07:43,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 319/1000 [03:46<08:01,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 320/1000 [03:46<07:29,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 321/1000 [03:47<07:46,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 322/1000 [03:48<07:49,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 323/1000 [03:49<07:48,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▏      | 324/1000 [03:49<07:57,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 32%|███▎      | 325/1000 [03:50<08:00,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 326/1000 [03:51<07:29,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 327/1000 [03:51<07:22,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 328/1000 [03:52<07:44,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 329/1000 [03:53<07:45,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 330/1000 [03:53<07:37,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 331/1000 [03:54<07:42,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 332/1000 [03:55<08:19,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 333/1000 [03:56<08:28,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 33%|███▎      | 334/1000 [03:56<08:14,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▎      | 335/1000 [03:57<08:22,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▎      | 336/1000 [03:58<08:10,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▎      | 337/1000 [03:59<08:18,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 338/1000 [03:59<07:54,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 339/1000 [04:00<07:53,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 340/1000 [04:01<07:42,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 341/1000 [04:02<08:00,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 342/1000 [04:02<07:16,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 343/1000 [04:03<07:02,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 344/1000 [04:03<06:50,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 34%|███▍      | 345/1000 [04:04<07:33,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▍      | 346/1000 [04:05<07:38,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▍      | 347/1000 [04:06<07:38,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▍      | 348/1000 [04:07<08:41,  1.25it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▍      | 349/1000 [04:07<08:43,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▌      | 350/1000 [04:08<08:42,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▌      | 351/1000 [04:09<08:01,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▌      | 352/1000 [04:10<08:07,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▌      | 353/1000 [04:10<07:40,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 35%|███▌      | 354/1000 [04:11<07:30,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 355/1000 [04:12<07:33,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 356/1000 [04:12<07:26,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 357/1000 [04:13<07:40,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 358/1000 [04:14<07:08,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 359/1000 [04:14<07:27,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 360/1000 [04:15<07:53,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 361/1000 [04:16<07:40,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▌      | 362/1000 [04:17<08:06,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▋      | 363/1000 [04:17<07:28,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▋      | 364/1000 [04:18<07:52,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 36%|███▋      | 365/1000 [04:19<07:45,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 366/1000 [04:20<07:57,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 367/1000 [04:20<07:29,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 368/1000 [04:21<07:10,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 369/1000 [04:22<07:38,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 370/1000 [04:22<07:58,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 371/1000 [04:23<07:54,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 372/1000 [04:24<07:38,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 373/1000 [04:24<06:53,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 37%|███▋      | 374/1000 [04:25<07:22,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 375/1000 [04:26<06:45,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 376/1000 [04:27<07:11,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 377/1000 [04:27<07:16,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 378/1000 [04:28<06:49,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 379/1000 [04:29<06:54,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 380/1000 [04:29<07:23,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 381/1000 [04:30<07:30,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 382/1000 [04:31<07:20,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 383/1000 [04:31<06:58,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 384/1000 [04:32<06:55,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 38%|███▊      | 385/1000 [04:33<07:07,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▊      | 386/1000 [04:34<07:24,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▊      | 387/1000 [04:34<07:41,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 388/1000 [04:35<07:50,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 389/1000 [04:36<07:53,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 390/1000 [04:37<07:55,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 391/1000 [04:38<08:16,  1.23it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 392/1000 [04:38<07:34,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 393/1000 [04:39<07:17,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 39%|███▉      | 394/1000 [04:40<07:08,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|███▉      | 395/1000 [04:41<07:51,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|███▉      | 396/1000 [04:41<07:46,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|███▉      | 397/1000 [04:42<07:22,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|███▉      | 398/1000 [04:43<07:03,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|███▉      | 399/1000 [04:43<06:49,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 400/1000 [04:44<07:03,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 401/1000 [04:45<06:42,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 402/1000 [04:45<07:10,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 403/1000 [04:46<07:40,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 404/1000 [04:47<06:53,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 40%|████      | 405/1000 [04:47<06:31,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 406/1000 [04:48<06:22,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 407/1000 [04:49<06:21,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 408/1000 [04:49<06:27,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 409/1000 [04:50<06:29,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 410/1000 [04:51<06:47,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 411/1000 [04:51<06:34,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████      | 412/1000 [04:52<07:21,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████▏     | 413/1000 [04:53<07:28,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 41%|████▏     | 414/1000 [04:54<07:21,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 415/1000 [04:54<06:56,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 416/1000 [04:55<07:44,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 417/1000 [04:56<07:28,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 418/1000 [04:57<06:40,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 419/1000 [04:57<06:55,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 420/1000 [04:58<06:55,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 421/1000 [04:59<06:39,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 422/1000 [04:59<06:30,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 423/1000 [05:00<06:44,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▏     | 424/1000 [05:01<06:53,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 42%|████▎     | 425/1000 [05:02<06:35,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 426/1000 [05:03<07:23,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 428/1000 [05:04<07:56,  1.20it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 429/1000 [05:05<07:51,  1.21it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 430/1000 [05:06<07:43,  1.23it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 431/1000 [05:07<08:06,  1.17it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 432/1000 [05:08<07:25,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 433/1000 [05:08<07:41,  1.23it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 43%|████▎     | 434/1000 [05:09<07:06,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▎     | 435/1000 [05:10<06:30,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▎     | 436/1000 [05:10<06:07,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▎     | 437/1000 [05:11<05:52,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 438/1000 [05:11<06:05,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 439/1000 [05:12<06:35,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 440/1000 [05:13<06:38,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 441/1000 [05:14<06:15,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 442/1000 [05:14<06:49,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 443/1000 [05:15<07:16,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 444/1000 [05:16<06:57,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 44%|████▍     | 445/1000 [05:17<06:34,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▍     | 446/1000 [05:17<06:21,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▍     | 447/1000 [05:18<06:23,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▍     | 448/1000 [05:19<06:34,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▍     | 449/1000 [05:19<06:16,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▌     | 450/1000 [05:20<06:24,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▌     | 451/1000 [05:21<05:51,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▌     | 452/1000 [05:21<05:48,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▌     | 453/1000 [05:22<05:40,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 45%|████▌     | 454/1000 [05:22<05:30,  1.65it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 455/1000 [05:23<05:47,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 456/1000 [05:24<06:00,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 457/1000 [05:25<06:34,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 458/1000 [05:25<06:06,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 459/1000 [05:26<06:09,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 460/1000 [05:27<07:04,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 461/1000 [05:28<07:37,  1.18it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▌     | 462/1000 [05:29<07:22,  1.22it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▋     | 463/1000 [05:29<06:52,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▋     | 464/1000 [05:30<06:22,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 46%|████▋     | 465/1000 [05:31<06:00,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 466/1000 [05:31<06:04,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 467/1000 [05:32<05:59,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 468/1000 [05:33<06:25,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 469/1000 [05:33<05:57,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 470/1000 [05:34<06:01,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 471/1000 [05:35<06:45,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 472/1000 [05:36<06:17,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 473/1000 [05:36<05:40,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 47%|████▋     | 474/1000 [05:37<05:29,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 475/1000 [05:37<05:50,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 476/1000 [05:38<05:45,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 477/1000 [05:39<05:50,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 478/1000 [05:39<05:43,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 479/1000 [05:40<05:39,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 480/1000 [05:41<05:49,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 481/1000 [05:41<05:32,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 482/1000 [05:42<05:24,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 483/1000 [05:43<06:16,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 484/1000 [05:43<06:06,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 48%|████▊     | 485/1000 [05:44<05:50,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▊     | 486/1000 [05:45<05:59,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▊     | 487/1000 [05:45<05:43,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 488/1000 [05:46<05:37,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 489/1000 [05:47<05:37,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 490/1000 [05:47<05:22,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 491/1000 [05:48<05:04,  1.67it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 492/1000 [05:48<05:15,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 493/1000 [05:49<05:24,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 49%|████▉     | 494/1000 [05:50<05:45,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|████▉     | 495/1000 [05:51<05:56,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|████▉     | 496/1000 [05:51<05:56,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|████▉     | 497/1000 [05:52<06:10,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|████▉     | 498/1000 [05:53<06:11,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|████▉     | 499/1000 [05:54<06:12,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 500/1000 [05:54<06:08,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 501/1000 [05:55<06:31,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 502/1000 [05:56<06:14,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 503/1000 [05:57<06:06,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 504/1000 [05:58<06:29,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 50%|█████     | 505/1000 [05:58<06:04,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 506/1000 [05:59<05:38,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 507/1000 [05:59<05:29,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 508/1000 [06:00<05:43,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 509/1000 [06:01<05:36,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 510/1000 [06:02<06:16,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 511/1000 [06:03<06:16,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████     | 512/1000 [06:03<06:05,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████▏    | 513/1000 [06:04<06:20,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 51%|█████▏    | 514/1000 [06:05<06:02,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 515/1000 [06:06<06:10,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 516/1000 [06:06<06:12,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 517/1000 [06:07<05:52,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 518/1000 [06:08<05:38,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 519/1000 [06:09<06:03,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 520/1000 [06:09<05:39,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 521/1000 [06:10<05:27,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 522/1000 [06:10<05:08,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 523/1000 [06:11<04:58,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▏    | 524/1000 [06:12<04:59,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 52%|█████▎    | 525/1000 [06:12<04:54,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 526/1000 [06:13<05:26,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 527/1000 [06:14<05:28,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 528/1000 [06:14<04:59,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 529/1000 [06:15<05:00,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 530/1000 [06:16<05:10,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 531/1000 [06:16<05:05,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 532/1000 [06:17<04:52,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 533/1000 [06:18<05:18,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 53%|█████▎    | 534/1000 [06:18<05:40,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▎    | 535/1000 [06:19<05:36,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▎    | 536/1000 [06:20<05:04,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▎    | 537/1000 [06:20<05:02,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 538/1000 [06:21<04:49,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 539/1000 [06:21<04:37,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 540/1000 [06:22<04:32,  1.69it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 541/1000 [06:23<04:31,  1.69it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 542/1000 [06:23<05:15,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 543/1000 [06:24<04:56,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 54%|█████▍    | 544/1000 [06:25<05:39,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▍    | 545/1000 [06:25<05:08,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▍    | 546/1000 [06:26<04:48,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▍    | 547/1000 [06:27<04:47,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▍    | 548/1000 [06:27<05:04,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▍    | 549/1000 [06:28<05:05,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▌    | 550/1000 [06:29<04:54,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▌    | 551/1000 [06:29<04:50,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▌    | 552/1000 [06:30<04:48,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▌    | 553/1000 [06:31<04:52,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 55%|█████▌    | 554/1000 [06:31<04:55,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 555/1000 [06:32<04:53,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 556/1000 [06:33<04:46,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 557/1000 [06:33<04:48,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 558/1000 [06:34<05:03,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 559/1000 [06:35<05:11,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 560/1000 [06:36<05:14,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 561/1000 [06:36<05:23,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▌    | 562/1000 [06:37<05:31,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▋    | 563/1000 [06:38<05:30,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▋    | 564/1000 [06:38<05:02,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 56%|█████▋    | 565/1000 [06:39<04:58,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 566/1000 [06:40<04:52,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 567/1000 [06:40<04:33,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 568/1000 [06:41<04:42,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 569/1000 [06:42<04:40,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 570/1000 [06:42<04:19,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 571/1000 [06:43<04:34,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 572/1000 [06:44<05:19,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 573/1000 [06:45<05:33,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▋    | 574/1000 [06:45<05:20,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 57%|█████▊    | 575/1000 [06:46<05:05,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 576/1000 [06:47<05:10,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 577/1000 [06:48<05:28,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 578/1000 [06:48<05:12,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 579/1000 [06:49<04:58,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 580/1000 [06:50<04:57,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 581/1000 [06:50<05:09,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 582/1000 [06:51<05:02,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 583/1000 [06:52<04:47,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 584/1000 [06:52<04:46,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 58%|█████▊    | 585/1000 [06:53<04:54,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▊    | 586/1000 [06:54<05:14,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▊    | 587/1000 [06:55<05:00,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 588/1000 [06:55<04:50,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 589/1000 [06:56<04:52,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 590/1000 [06:57<04:33,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 591/1000 [06:57<04:43,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 592/1000 [06:58<04:42,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 593/1000 [06:59<04:42,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 59%|█████▉    | 594/1000 [07:00<04:58,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|█████▉    | 595/1000 [07:00<04:57,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|█████▉    | 596/1000 [07:01<04:41,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|█████▉    | 597/1000 [07:02<04:43,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|█████▉    | 598/1000 [07:02<04:38,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|█████▉    | 599/1000 [07:04<05:45,  1.16it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 600/1000 [07:04<05:42,  1.17it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 601/1000 [07:05<05:22,  1.24it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 602/1000 [07:06<05:04,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 603/1000 [07:07<05:02,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 604/1000 [07:08<05:25,  1.22it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 60%|██████    | 605/1000 [07:08<04:48,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 606/1000 [07:09<04:30,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 607/1000 [07:09<04:28,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 608/1000 [07:10<04:34,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 609/1000 [07:11<04:31,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 610/1000 [07:11<04:09,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 611/1000 [07:12<03:59,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████    | 612/1000 [07:12<03:59,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████▏   | 613/1000 [07:13<03:59,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 61%|██████▏   | 614/1000 [07:14<03:56,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 615/1000 [07:14<04:01,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 616/1000 [07:15<04:03,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 617/1000 [07:16<04:13,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 618/1000 [07:16<04:09,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 619/1000 [07:17<04:20,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 620/1000 [07:18<04:13,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 621/1000 [07:19<04:40,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 622/1000 [07:19<04:52,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 623/1000 [07:20<04:49,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▏   | 624/1000 [07:21<05:15,  1.19it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 62%|██████▎   | 625/1000 [07:22<05:27,  1.15it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 626/1000 [07:23<05:08,  1.21it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 627/1000 [07:23<04:35,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 628/1000 [07:24<04:29,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 629/1000 [07:25<04:24,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 630/1000 [07:26<04:25,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 631/1000 [07:26<04:40,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 632/1000 [07:27<04:33,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 633/1000 [07:28<04:32,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 63%|██████▎   | 634/1000 [07:29<04:29,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▎   | 635/1000 [07:29<04:39,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▎   | 636/1000 [07:30<04:26,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▎   | 637/1000 [07:31<04:17,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 638/1000 [07:31<04:11,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 639/1000 [07:32<04:02,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 640/1000 [07:33<03:53,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 641/1000 [07:33<03:51,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 642/1000 [07:34<03:49,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 643/1000 [07:35<03:53,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 644/1000 [07:35<03:45,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 64%|██████▍   | 645/1000 [07:36<04:14,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▍   | 646/1000 [07:37<03:58,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▍   | 647/1000 [07:37<04:04,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▍   | 648/1000 [07:38<03:57,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▍   | 649/1000 [07:39<04:17,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▌   | 650/1000 [07:40<04:28,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▌   | 651/1000 [07:40<04:14,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▌   | 652/1000 [07:41<04:06,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▌   | 653/1000 [07:42<03:54,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 65%|██████▌   | 654/1000 [07:42<03:42,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 655/1000 [07:43<03:57,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 656/1000 [07:43<03:37,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 657/1000 [07:44<03:59,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 658/1000 [07:45<04:03,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 659/1000 [07:46<03:47,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 660/1000 [07:46<03:36,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 661/1000 [07:47<03:54,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▌   | 662/1000 [07:48<03:54,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▋   | 663/1000 [07:49<04:06,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▋   | 664/1000 [07:49<04:13,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 66%|██████▋   | 665/1000 [07:50<04:10,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 666/1000 [07:51<03:56,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 667/1000 [07:51<03:56,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 668/1000 [07:52<03:52,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 669/1000 [07:53<04:02,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 670/1000 [07:54<03:49,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 671/1000 [07:54<03:29,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 672/1000 [07:55<03:28,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 673/1000 [07:55<03:38,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 67%|██████▋   | 674/1000 [07:56<03:38,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 675/1000 [07:57<03:46,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 676/1000 [07:57<03:41,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 677/1000 [07:58<03:39,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 678/1000 [07:59<03:53,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 679/1000 [07:59<03:28,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 680/1000 [08:00<03:15,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 681/1000 [08:01<03:11,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 682/1000 [08:01<03:21,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 683/1000 [08:02<03:22,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 684/1000 [08:03<03:35,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 68%|██████▊   | 685/1000 [08:03<03:35,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▊   | 686/1000 [08:04<03:21,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▊   | 687/1000 [08:05<03:17,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 688/1000 [08:05<03:20,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 689/1000 [08:06<03:20,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 690/1000 [08:07<03:24,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 691/1000 [08:07<03:29,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 692/1000 [08:08<03:56,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 693/1000 [08:09<03:50,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 69%|██████▉   | 694/1000 [08:10<03:50,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|██████▉   | 695/1000 [08:11<04:02,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|██████▉   | 696/1000 [08:11<04:06,  1.23it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|██████▉   | 697/1000 [08:12<03:50,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|██████▉   | 698/1000 [08:13<03:55,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|██████▉   | 699/1000 [08:13<03:32,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 700/1000 [08:14<03:23,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 701/1000 [08:15<03:09,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 702/1000 [08:15<03:23,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 703/1000 [08:16<03:16,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 704/1000 [08:17<03:26,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 70%|███████   | 705/1000 [08:18<03:29,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 706/1000 [08:18<03:34,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 707/1000 [08:19<03:49,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 708/1000 [08:20<03:42,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 709/1000 [08:20<03:25,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 710/1000 [08:21<03:38,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 711/1000 [08:22<03:33,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████   | 712/1000 [08:23<03:42,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████▏  | 713/1000 [08:24<03:32,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 71%|███████▏  | 714/1000 [08:24<03:28,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 715/1000 [08:25<03:31,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 716/1000 [08:26<03:21,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 717/1000 [08:26<03:14,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 718/1000 [08:27<03:11,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 719/1000 [08:28<03:41,  1.27it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 720/1000 [08:29<03:29,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 721/1000 [08:29<03:21,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 722/1000 [08:30<03:40,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 723/1000 [08:31<03:19,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▏  | 724/1000 [08:32<03:16,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 72%|███████▎  | 725/1000 [08:32<03:02,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 726/1000 [08:33<03:02,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 727/1000 [08:34<03:22,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 728/1000 [08:35<03:30,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 729/1000 [08:35<03:31,  1.28it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 730/1000 [08:36<03:22,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 731/1000 [08:36<03:01,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 732/1000 [08:37<03:02,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 733/1000 [08:38<03:13,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 73%|███████▎  | 734/1000 [08:39<03:08,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▎  | 735/1000 [08:39<03:14,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▎  | 736/1000 [08:40<03:15,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▎  | 737/1000 [08:41<03:15,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 738/1000 [08:42<03:22,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 739/1000 [08:42<03:09,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 740/1000 [08:43<02:58,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 741/1000 [08:44<02:49,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 742/1000 [08:44<02:37,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 743/1000 [08:45<02:49,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 744/1000 [08:45<02:42,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 74%|███████▍  | 745/1000 [08:46<02:53,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▍  | 746/1000 [08:47<03:06,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▍  | 747/1000 [08:48<03:02,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▍  | 748/1000 [08:48<02:58,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▍  | 749/1000 [08:49<02:41,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▌  | 750/1000 [08:50<02:34,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▌  | 751/1000 [08:50<02:41,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▌  | 752/1000 [08:51<02:33,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▌  | 753/1000 [08:51<02:29,  1.65it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 75%|███████▌  | 754/1000 [08:52<02:19,  1.77it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 755/1000 [08:52<02:21,  1.73it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 756/1000 [08:53<02:36,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 757/1000 [08:54<02:44,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 758/1000 [08:55<02:51,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 759/1000 [08:56<02:53,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 760/1000 [08:56<02:41,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 761/1000 [08:57<02:31,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▌  | 762/1000 [08:57<02:42,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▋  | 763/1000 [08:58<02:31,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▋  | 764/1000 [08:59<02:23,  1.65it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 76%|███████▋  | 765/1000 [08:59<02:33,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 766/1000 [09:00<02:24,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 767/1000 [09:00<02:24,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 768/1000 [09:01<02:36,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 769/1000 [09:02<02:37,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 770/1000 [09:03<02:42,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 771/1000 [09:03<02:32,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 772/1000 [09:04<02:34,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 773/1000 [09:05<02:59,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 77%|███████▋  | 774/1000 [09:06<02:55,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 775/1000 [09:06<02:50,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 776/1000 [09:07<02:52,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 777/1000 [09:08<03:00,  1.23it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 778/1000 [09:09<02:41,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 779/1000 [09:10<02:45,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 780/1000 [09:10<02:37,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 781/1000 [09:11<02:25,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 782/1000 [09:11<02:14,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 783/1000 [09:12<02:27,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 784/1000 [09:13<02:36,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 78%|███████▊  | 785/1000 [09:14<02:36,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▊  | 786/1000 [09:14<02:25,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▊  | 787/1000 [09:15<02:27,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 788/1000 [09:16<02:23,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 789/1000 [09:16<02:35,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 790/1000 [09:17<02:29,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 791/1000 [09:18<02:20,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 792/1000 [09:18<02:13,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 793/1000 [09:19<02:13,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 79%|███████▉  | 794/1000 [09:19<02:08,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|███████▉  | 795/1000 [09:20<02:05,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|███████▉  | 796/1000 [09:21<02:02,  1.67it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|███████▉  | 797/1000 [09:21<02:02,  1.65it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|███████▉  | 798/1000 [09:22<02:10,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|███████▉  | 799/1000 [09:23<02:06,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 800/1000 [09:23<02:15,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 801/1000 [09:24<02:18,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 802/1000 [09:25<02:07,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 803/1000 [09:25<02:04,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 804/1000 [09:26<02:18,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 80%|████████  | 805/1000 [09:27<02:20,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 806/1000 [09:27<02:15,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 807/1000 [09:28<02:23,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 808/1000 [09:29<02:20,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 809/1000 [09:30<02:19,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 810/1000 [09:30<02:08,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 811/1000 [09:31<02:00,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████  | 812/1000 [09:31<01:55,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████▏ | 813/1000 [09:32<01:49,  1.71it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 81%|████████▏ | 814/1000 [09:33<01:49,  1.70it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 815/1000 [09:33<01:50,  1.67it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 816/1000 [09:34<01:56,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 817/1000 [09:35<01:58,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 818/1000 [09:35<01:53,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 819/1000 [09:36<01:57,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 820/1000 [09:36<01:51,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 821/1000 [09:37<01:43,  1.72it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 822/1000 [09:38<01:49,  1.63it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 823/1000 [09:38<01:43,  1.70it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▏ | 824/1000 [09:39<01:39,  1.77it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 82%|████████▎ | 825/1000 [09:40<01:59,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 826/1000 [09:40<02:00,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 827/1000 [09:41<02:06,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 828/1000 [09:42<02:10,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 829/1000 [09:42<01:59,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 830/1000 [09:43<01:56,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 831/1000 [09:44<01:55,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 832/1000 [09:44<01:52,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 833/1000 [09:45<01:51,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 83%|████████▎ | 834/1000 [09:46<01:43,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▎ | 835/1000 [09:46<01:50,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▎ | 836/1000 [09:47<01:53,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▎ | 837/1000 [09:48<01:51,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 838/1000 [09:48<01:49,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 839/1000 [09:49<01:49,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 840/1000 [09:50<01:56,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 841/1000 [09:51<01:57,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 842/1000 [09:51<01:52,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 843/1000 [09:52<01:40,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 844/1000 [09:52<01:34,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 84%|████████▍ | 845/1000 [09:53<01:41,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▍ | 846/1000 [09:54<01:45,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▍ | 847/1000 [09:55<01:46,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▍ | 848/1000 [09:55<01:42,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▍ | 849/1000 [09:56<01:35,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▌ | 850/1000 [09:57<01:42,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▌ | 851/1000 [09:57<01:42,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▌ | 852/1000 [09:58<01:35,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▌ | 853/1000 [09:58<01:32,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 85%|████████▌ | 854/1000 [09:59<01:38,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 855/1000 [10:00<01:29,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 856/1000 [10:00<01:28,  1.64it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 857/1000 [10:01<01:24,  1.70it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 858/1000 [10:02<01:30,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 859/1000 [10:02<01:24,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 860/1000 [10:03<01:32,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 861/1000 [10:04<01:35,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▌ | 862/1000 [10:04<01:33,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▋ | 863/1000 [10:05<01:46,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▋ | 864/1000 [10:06<01:42,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 86%|████████▋ | 865/1000 [10:07<01:34,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 866/1000 [10:07<01:24,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 867/1000 [10:08<01:26,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 868/1000 [10:09<01:30,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 869/1000 [10:09<01:24,  1.55it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 870/1000 [10:10<01:21,  1.60it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 871/1000 [10:11<01:30,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 872/1000 [10:11<01:29,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 873/1000 [10:12<01:27,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 87%|████████▋ | 874/1000 [10:13<01:29,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 875/1000 [10:13<01:30,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 876/1000 [10:14<01:26,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 877/1000 [10:15<01:28,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 878/1000 [10:16<01:27,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 879/1000 [10:16<01:26,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 880/1000 [10:17<01:32,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 881/1000 [10:18<01:28,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 882/1000 [10:18<01:20,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 883/1000 [10:19<01:17,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 884/1000 [10:20<01:15,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 88%|████████▊ | 885/1000 [10:20<01:21,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▊ | 886/1000 [10:21<01:30,  1.25it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▊ | 887/1000 [10:22<01:27,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 888/1000 [10:23<01:21,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 889/1000 [10:24<01:25,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 890/1000 [10:25<01:27,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 891/1000 [10:25<01:22,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 892/1000 [10:26<01:25,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 893/1000 [10:27<01:27,  1.22it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 89%|████████▉ | 894/1000 [10:28<01:28,  1.20it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|████████▉ | 895/1000 [10:28<01:21,  1.29it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|████████▉ | 896/1000 [10:29<01:15,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|████████▉ | 897/1000 [10:30<01:12,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|████████▉ | 898/1000 [10:31<01:14,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|████████▉ | 899/1000 [10:31<01:16,  1.32it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 900/1000 [10:32<01:13,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 901/1000 [10:33<01:18,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 902/1000 [10:33<01:09,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 903/1000 [10:34<01:07,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 904/1000 [10:35<01:04,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 90%|█████████ | 905/1000 [10:35<01:00,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 906/1000 [10:36<01:01,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 907/1000 [10:37<01:03,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 908/1000 [10:38<01:05,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 909/1000 [10:38<01:03,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 910/1000 [10:39<01:05,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 911/1000 [10:39<00:58,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████ | 912/1000 [10:40<01:01,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████▏| 913/1000 [10:41<00:56,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 91%|█████████▏| 914/1000 [10:41<00:54,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 915/1000 [10:42<00:59,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 916/1000 [10:43<01:01,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 917/1000 [10:44<01:01,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 918/1000 [10:45<00:59,  1.38it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 919/1000 [10:45<00:54,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 920/1000 [10:46<00:53,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 921/1000 [10:46<00:52,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 922/1000 [10:47<00:52,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 923/1000 [10:48<00:52,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▏| 924/1000 [10:48<00:52,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 92%|█████████▎| 925/1000 [10:49<00:51,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 926/1000 [10:50<00:51,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 927/1000 [10:50<00:47,  1.53it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 928/1000 [10:51<00:46,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 929/1000 [10:52<00:46,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 930/1000 [10:52<00:48,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 931/1000 [10:53<00:49,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 932/1000 [10:54<00:46,  1.46it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 933/1000 [10:55<00:47,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 93%|█████████▎| 934/1000 [10:55<00:49,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

/usr/local/lib/python3.12/dist-packages/neurokit2/signal/signal_period.py:83: NeuroKitWarning: Too few peaks detected to compute the rate. Returning empty vector.
  warn(
 94%|█████████▎| 935/1000 [10:56<00:47,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▎| 936/1000 [10:57<00:47,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▎| 937/1000 [10:58<00:45,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 938/1000 [10:58<00:46,  1.35it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 939/1000 [10:59<00:46,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 940/1000 [11:00<00:47,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 941/1000 [11:01<00:49,  1.18it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 942/1000 [11:02<00:44,  1.31it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 943/1000 [11:02<00:43,  1.30it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 944/1000 [11:03<00:44,  1.26it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 94%|█████████▍| 945/1000 [11:04<00:39,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▍| 946/1000 [11:05<00:39,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▍| 947/1000 [11:05<00:36,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▍| 948/1000 [11:06<00:35,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▍| 949/1000 [11:07<00:34,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▌| 950/1000 [11:07<00:35,  1.42it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▌| 951/1000 [11:08<00:35,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▌| 952/1000 [11:09<00:34,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▌| 953/1000 [11:09<00:33,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 95%|█████████▌| 954/1000 [11:10<00:31,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 955/1000 [11:11<00:32,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 956/1000 [11:12<00:31,  1.39it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 957/1000 [11:12<00:30,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 958/1000 [11:13<00:30,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 959/1000 [11:14<00:29,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 960/1000 [11:14<00:25,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 961/1000 [11:15<00:28,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▌| 962/1000 [11:16<00:27,  1.37it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▋| 963/1000 [11:16<00:25,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▋| 964/1000 [11:17<00:23,  1.56it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 96%|█████████▋| 965/1000 [11:18<00:24,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 966/1000 [11:18<00:23,  1.45it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 967/1000 [11:19<00:24,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 968/1000 [11:20<00:23,  1.36it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 969/1000 [11:21<00:21,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 970/1000 [11:21<00:20,  1.47it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 971/1000 [11:22<00:18,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 972/1000 [11:23<00:18,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 973/1000 [11:23<00:16,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 97%|█████████▋| 974/1000 [11:24<00:16,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 975/1000 [11:24<00:15,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 976/1000 [11:25<00:15,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 977/1000 [11:26<00:14,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 978/1000 [11:26<00:13,  1.58it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 979/1000 [11:27<00:14,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 980/1000 [11:28<00:14,  1.34it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 981/1000 [11:29<00:14,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 982/1000 [11:30<00:13,  1.33it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 983/1000 [11:30<00:12,  1.41it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 984/1000 [11:31<00:11,  1.40it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 98%|█████████▊| 985/1000 [11:31<00:09,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▊| 986/1000 [11:32<00:08,  1.61it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▊| 987/1000 [11:33<00:07,  1.66it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 988/1000 [11:33<00:07,  1.57it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 989/1000 [11:34<00:07,  1.51it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 990/1000 [11:35<00:06,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 991/1000 [11:35<00:06,  1.44it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 992/1000 [11:36<00:05,  1.49it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 993/1000 [11:37<00:04,  1.48it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

 99%|█████████▉| 994/1000 [11:37<00:03,  1.54it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|█████████▉| 995/1000 [11:38<00:03,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|█████████▉| 996/1000 [11:39<00:02,  1.59it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|█████████▉| 997/1000 [11:39<00:01,  1.62it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|█████████▉| 998/1000 [11:40<00:01,  1.50it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|█████████▉| 999/1000 [11:41<00:00,  1.52it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)

100%|██████████| 1000/1000 [11:41<00:00,  1.43it/s]

Raw signal shape: (1000, 12)
Normalized signal shape: (1000, 12)
Model input shape: (1, 1000, 12)
Created agent examples: 1000
Failed examples: 0

In [ ]:
rows = []

for result in agent_training_results:
    probs = result["ptbxl_classifier_output"]["probabilities"]

    rows.append({
        "ecg_id": result["ecg_id"],
        "true_diagnostic_class_main": result["true_diagnostic_class_main"],
        "true_diagnostic_classes": result["true_diagnostic_classes"],
        "heart_rate_bpm": result["rhythm_tool_output"].get("estimated_heart_rate_bpm", None),
        "rhythm_regularity": result["rhythm_tool_output"].get("rhythm_regularity", None),
        "number_of_r_peaks": result["rhythm_tool_output"].get("number_of_r_peaks", None),
        "predicted_labels": ", ".join(result["ptbxl_classifier_output"].get("predicted_labels", [])),
        "top_class": result["ptbxl_classifier_output"].get("top_class", None),
        "prob_NORM": probs.get("NORM", None),
        "prob_MI": probs.get("MI", None),
        "prob_STTC": probs.get("STTC", None),
        "prob_CD": probs.get("CD", None),
        "prob_HYP": probs.get("HYP", None),
        "agent_summary": result["agent_summary"]
    })

agent_outputs_df = pd.DataFrame(rows)

agent_outputs_path = RESULTS_DIR / "ecg_agent_tool_outputs_1000.csv"
agent_outputs_df.to_csv(agent_outputs_path, index=False)

display(agent_outputs_df.head())
print("Saved agent tool outputs to:", agent_outputs_path)
print("Shape:", agent_outputs_df.shape)

,ecg_id,true_diagnostic_class_main,true_diagnostic_classes,heart_rate_bpm,rhythm_regularity,number_of_r_peaks,predicted_labels,top_class,prob_NORM,prob_MI,prob_STTC,prob_CD,prob_HYP,agent_summary
0,5726,NORM,['NORM'],65.861690,likely regular,11.0,NORM,NORM,0.992056,0.000727,0.001420,0.003179,0.000482,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
1,19957,NORM,['NORM'],67.950170,irregular,11.0,NORM,NORM,0.944263,0.011218,0.011116,0.029648,0.003430,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
2,12451,NORM,['NORM'],62.790698,likely regular,10.0,NORM,NORM,0.974085,0.006688,0.010100,0.001923,0.000437,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
3,12707,NORM,['NORM'],49.763033,likely regular,8.0,"NORM, HYP",HYP,0.530302,0.003572,0.012525,0.005492,0.640136,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
4,13364,NORM,['NORM'],58.679707,likely regular,9.0,NORM,NORM,0.946550,0.027738,0.005418,0.023868,0.000333,ECG Agent Summary\n\n1. Rhythm assessment\n- L...

Saved agent tool outputs to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_agent_tool_outputs_1000.csv
Shape: (1000, 14)

In [ ]:
LABEL_MEANINGS = {
    "NORM": "normal ECG",
    "MI": "myocardial infarction",
    "STTC": "ST/T changes",
    "CD": "conduction disturbance",
    "HYP": "hypertrophy"
}

def make_agent_prompt(result):
    rhythm = result["rhythm_tool_output"]
    classifier = result["ptbxl_classifier_output"]
    probs = classifier["probabilities"]

    prompt = f"""
You are an ECG agent. Your task is to integrate outputs from specialized ECG tools and generate a structured, cautious explanation.

Important rules:
- Do not claim this is a clinical diagnosis.
- Explain that the rhythm tool provides rhythm features only.
- Explain the meaning of predicted PTB-XL labels.
- Mention uncertainty if tool outputs are limited.

Tool 1: Rhythm feature tool
- Lead used: {rhythm.get("lead_used", "unknown")}
- Number of detected R-peaks: {rhythm.get("number_of_r_peaks", "unknown")}
- Estimated heart rate: {rhythm.get("estimated_heart_rate_bpm", "unavailable")}
- Rhythm regularity: {rhythm.get("rhythm_regularity", "unknown")}
- Scope: {rhythm.get("interpretation_scope", "Rhythm feature assessment only.")}

Tool 2: Pretrained PTB-XL signal classifier
- Predicted labels above threshold: {", ".join(classifier.get("predicted_labels", []))}
- Top class: {classifier.get("top_class", "unknown")}
- Class probabilities:
  - NORM: {probs.get("NORM", None)}
  - MI: {probs.get("MI", None)}
  - STTC: {probs.get("STTC", None)}
  - CD: {probs.get("CD", None)}
  - HYP: {probs.get("HYP", None)}

Generate a structured ECG agent summary.
""".strip()

    return prompt


def make_agent_target(result):
    return result["agent_summary"]


agent_examples = []

for result in agent_training_results:
    agent_examples.append({
        "ecg_id": result["ecg_id"],
        "prompt": make_agent_prompt(result),
        "response": make_agent_target(result)
    })

agent_dataset_path = RESULTS_DIR / "qwen_ecg_agent_supervised_dataset_1000.jsonl"

with open(agent_dataset_path, "w") as f:
    for ex in agent_examples:
        f.write(json.dumps(ex) + "\n")

print("Saved agent supervised dataset to:", agent_dataset_path)
print("Number of examples:", len(agent_examples))

print("\nExample prompt:\n")
print(agent_examples[0]["prompt"])

print("\nExample response:\n")
print(agent_examples[0]["response"])

Saved agent supervised dataset to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_agent_supervised_dataset_1000.jsonl
Number of examples: 1000

Example prompt:

You are an ECG agent. Your task is to integrate outputs from specialized ECG tools and generate a structured, cautious explanation.

Important rules:
- Do not claim this is a clinical diagnosis.
- Explain that the rhythm tool provides rhythm features only.
- Explain the meaning of predicted PTB-XL labels.
- Mention uncertainty if tool outputs are limited.

Tool 1: Rhythm feature tool
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 65.86169045005488
- Rhythm regularity: likely regular
- Scope: Rhythm feature assessment only; not a full arrhythmia diagnosis.

Tool 2: Pretrained PTB-XL signal classifier
- Predicted labels above threshold: NORM
- Top class: NORM
- Class probabilities:
  - NORM: 0.9920564293861389
  - MI: 0.0007271073991432786
  - STTC: 0.001419559819623828
  - CD: 0.003178607439622283
  - HYP: 0.00048198708100244403

Generate a structured ECG agent summary.

Example response:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 11
- Estimated heart rate: 65.9 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: NORM
- Highest probability class: NORM (normal ECG), probability 0.992

Class probabilities:
- NORM (normal ECG): 0.992
- CD (conduction disturbance): 0.003
- STTC (ST/T changes): 0.001
- MI (myocardial infarction): 0.001
- HYP (hypertrophy): 0.000

3. Integrated interpretation
- The pretrained signal classifier primarily suggests a normal ECG pattern.
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
!pip install -q transformers accelerate datasets peft bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 9.7 MB/s eta 0:00:00

In [ ]:
from datasets import load_dataset

agent_dataset = load_dataset(
    "json",
    data_files=str(agent_dataset_path),
    split="train"
)

agent_dataset = agent_dataset.train_test_split(test_size=0.1, seed=42)

train_agent = agent_dataset["train"]
eval_agent = agent_dataset["test"]

print(train_agent)
print(eval_agent)
print(train_agent[0])

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['ecg_id', 'prompt', 'response'],
    num_rows: 900
})
Dataset({
    features: ['ecg_id', 'prompt', 'response'],
    num_rows: 100
})
{'ecg_id': 19490, 'prompt': 'You are an ECG agent. Your task is to integrate outputs from specialized ECG tools and generate a structured, cautious explanation.\n\nImportant rules:\n- Do not claim this is a clinical diagnosis.\n- Explain that the rhythm tool provides rhythm features only.\n- Explain the meaning of predicted PTB-XL labels.\n- Mention uncertainty if tool outputs are limited.\n\nTool 1: Rhythm feature tool\n- Lead used: II\n- Number of detected R-peaks: 15\n- Estimated heart rate: 89.36170212765957\n- Rhythm regularity: likely regular\n- Scope: Rhythm feature assessment only; not a full arrhythmia diagnosis.\n\nTool 2: Pretrained PTB-XL signal classifier\n- Predicted labels above threshold: MI\n- Top class: MI\n- Class probabilities:\n  - NORM: 0.12436529248952866\n  - MI: 0.8231194615364075\n  - STTC: 0.01939145103096962\n  - CD: 0.0028020991012454033\n  - HYP: 0.002631847746670246\n\nGenerate a structured ECG agent summary.', 'response': 'ECG Agent Summary\n\n1. Rhythm assessment\n- Lead used: II\n- Number of detected R-peaks: 15\n- Estimated heart rate: 89.4 bpm\n- Rhythm regularity: likely regular\n- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.\n\n2. Diagnostic superclass classification\n- Predicted label(s) above threshold: MI\n- Highest probability class: MI (myocardial infarction), probability 0.823\n\nClass probabilities:\n- MI (myocardial infarction): 0.823\n- NORM (normal ECG): 0.124\n- STTC (ST/T changes): 0.019\n- CD (conduction disturbance): 0.003\n- HYP (hypertrophy): 0.003\n\n3. Integrated interpretation\n- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).\n- The rhythm feature tool provides supportive rhythm information based on R-peak detection.\n- This is a research prototype and not a clinical diagnosis.'}

In [ ]:
import gc
import torch

for var_name in ["base_model_agent", "model_agent_lora", "trainer_agent"]:
    if var_name in globals():
        del globals()[var_name]

gc.collect()
torch.cuda.empty_cache()

print("Memory cleared.")

Memory cleared.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model_name_agent = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name_agent)

bnb_config_agent = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

base_model_agent = AutoModelForCausalLM.from_pretrained(
    model_name_agent,
    quantization_config=bnb_config_agent,
    device_map="auto"
)

base_model_agent = prepare_model_for_kbit_training(base_model_agent)

lora_config_agent = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model_agent_lora = get_peft_model(base_model_agent, lora_config_agent)
model_agent_lora.print_trainable_parameters()

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/default/ops.py:223: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cpu/ops.py:36: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

In [ ]:
def format_agent_example(example):
    messages = [
        {
            "role": "system",
            "content": "You are an ECG agent that integrates outputs from specialized ECG tools and provides cautious structured explanations."
        },
        {
            "role": "user",
            "content": example["prompt"]
        },
        {
            "role": "assistant",
            "content": example["response"]
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

    return {"text": text}


train_agent_formatted = train_agent.map(format_agent_example)
eval_agent_formatted = eval_agent.map(format_agent_example)

def tokenize_agent(example):
    tokenized = tokenizer(
        example["text"],
        truncation=True,
        max_length=1024,
        padding=False
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

train_agent_tokenized = train_agent_formatted.map(
    tokenize_agent,
    remove_columns=train_agent_formatted.column_names
)

eval_agent_tokenized = eval_agent_formatted.map(
    tokenize_agent,
    remove_columns=eval_agent_formatted.column_names
)

print(train_agent_tokenized)
print(eval_agent_tokenized)

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 900
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 100
})

In [ ]:
from transformers import Trainer, TrainingArguments, DataCollatorForLanguageModeling

data_collator_agent = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

output_dir_agent = str(RESULTS_DIR / "qwen_ecg_tool_agent_lora_1000")

training_args_agent = TrainingArguments(
    output_dir=output_dir_agent,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,
    num_train_epochs=2,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    report_to="none",
    optim="paged_adamw_8bit"
)

trainer_agent = Trainer(
    model=model_agent_lora,
    args=training_args_agent,
    train_dataset=train_agent_tokenized,
    eval_dataset=eval_agent_tokenized,
    data_collator=data_collator_agent
)

print("Qwen ECG tool-agent trainer ready.")

Qwen ECG tool-agent trainer ready.

In [ ]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No GPU available.")

CUDA available: True
GPU: Tesla T4

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
PTBXL_DIR = DATA_DIR / "ptbxl_mini"

agent_dataset_path = RESULTS_DIR / "qwen_ecg_agent_supervised_dataset_1000.jsonl"

print("Agent dataset exists:", agent_dataset_path.exists())
print("Path:", agent_dataset_path)

Agent dataset exists: True
Path: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_agent_supervised_dataset_1000.jsonl

In [ ]:
!pip install -q transformers accelerate datasets peft bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.7 MB/s eta 0:00:00

In [ ]:
from datasets import load_dataset

agent_dataset = load_dataset(
    "json",
    data_files=str(agent_dataset_path),
    split="train"
)

agent_dataset = agent_dataset.train_test_split(test_size=0.1, seed=42)

train_agent = agent_dataset["train"]
eval_agent = agent_dataset["test"]

print(train_agent)
print(eval_agent)
print(train_agent[0])

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['ecg_id', 'prompt', 'response'],
    num_rows: 900
})
Dataset({
    features: ['ecg_id', 'prompt', 'response'],
    num_rows: 100
})
{'ecg_id': 19490, 'prompt': 'You are an ECG agent. Your task is to integrate outputs from specialized ECG tools and generate a structured, cautious explanation.\n\nImportant rules:\n- Do not claim this is a clinical diagnosis.\n- Explain that the rhythm tool provides rhythm features only.\n- Explain the meaning of predicted PTB-XL labels.\n- Mention uncertainty if tool outputs are limited.\n\nTool 1: Rhythm feature tool\n- Lead used: II\n- Number of detected R-peaks: 15\n- Estimated heart rate: 89.36170212765957\n- Rhythm regularity: likely regular\n- Scope: Rhythm feature assessment only; not a full arrhythmia diagnosis.\n\nTool 2: Pretrained PTB-XL signal classifier\n- Predicted labels above threshold: MI\n- Top class: MI\n- Class probabilities:\n  - NORM: 0.12436529248952866\n  - MI: 0.8231194615364075\n  - STTC: 0.01939145103096962\n  - CD: 0.0028020991012454033\n  - HYP: 0.002631847746670246\n\nGenerate a structured ECG agent summary.', 'response': 'ECG Agent Summary\n\n1. Rhythm assessment\n- Lead used: II\n- Number of detected R-peaks: 15\n- Estimated heart rate: 89.4 bpm\n- Rhythm regularity: likely regular\n- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.\n\n2. Diagnostic superclass classification\n- Predicted label(s) above threshold: MI\n- Highest probability class: MI (myocardial infarction), probability 0.823\n\nClass probabilities:\n- MI (myocardial infarction): 0.823\n- NORM (normal ECG): 0.124\n- STTC (ST/T changes): 0.019\n- CD (conduction disturbance): 0.003\n- HYP (hypertrophy): 0.003\n\n3. Integrated interpretation\n- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).\n- The rhythm feature tool provides supportive rhythm information based on R-peak detection.\n- This is a research prototype and not a clinical diagnosis.'}

In [ ]:
import gc
import torch

gc.collect()
torch.cuda.empty_cache()

print("CUDA available:", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))

CUDA available: True
Device: Tesla T4

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

model_name_agent = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name_agent)

bnb_config_agent = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

base_model_agent = AutoModelForCausalLM.from_pretrained(
    model_name_agent,
    quantization_config=bnb_config_agent,
    device_map="auto"
)

base_model_agent = prepare_model_for_kbit_training(base_model_agent)

lora_config_agent = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model_agent_lora = get_peft_model(base_model_agent, lora_config_agent)
model_agent_lora.print_trainable_parameters()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

In [ ]:
def format_agent_example(example):
    messages = [
        {
            "role": "system",
            "content": "You are an ECG agent that integrates outputs from specialized ECG tools and provides cautious structured explanations."
        },
        {
            "role": "user",
            "content": example["prompt"]
        },
        {
            "role": "assistant",
            "content": example["response"]
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

    return {"text": text}


train_agent_formatted = train_agent.map(format_agent_example)
eval_agent_formatted = eval_agent.map(format_agent_example)

def tokenize_agent(example):
    tokenized = tokenizer(
        example["text"],
        truncation=True,
        max_length=1024,
        padding=False
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

train_agent_tokenized = train_agent_formatted.map(
    tokenize_agent,
    remove_columns=train_agent_formatted.column_names
)

eval_agent_tokenized = eval_agent_formatted.map(
    tokenize_agent,
    remove_columns=eval_agent_formatted.column_names
)

print(train_agent_tokenized)
print(eval_agent_tokenized)

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/900 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 900
})
Dataset({
    features: ['input_ids', 'attention_mask', 'labels'],
    num_rows: 100
})

In [ ]:
from transformers import Trainer, TrainingArguments, DataCollatorForLanguageModeling

data_collator_agent = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

output_dir_agent = str(RESULTS_DIR / "qwen_ecg_tool_agent_lora_1000")

training_args_agent = TrainingArguments(
    output_dir=output_dir_agent,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,
    num_train_epochs=2,
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    report_to="none",
    optim="paged_adamw_8bit"
)

trainer_agent = Trainer(
    model=model_agent_lora,
    args=training_args_agent,
    train_dataset=train_agent_tokenized,
    eval_dataset=eval_agent_tokenized,
    data_collator=data_collator_agent
)

print("Qwen ECG tool-agent trainer ready.")

Qwen ECG tool-agent trainer ready.

In [ ]:
trainer_agent.train()

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

TrainOutput(global_step=450, training_loss=0.5203944651285807, metrics={'train_runtime': 844.127, 'train_samples_per_second': 2.132, 'train_steps_per_second': 0.533, 'total_flos': 2291100222850560.0, 'train_loss': 0.5203944651285807, 'epoch': 2.0})

In [ ]:
save_dir_agent = RESULTS_DIR / "qwen_ecg_tool_agent_lora_1000_final"

trainer_agent.model.save_pretrained(save_dir_agent)
tokenizer.save_pretrained(save_dir_agent)

print("Saved Qwen ECG tool-agent LoRA adapter to:", save_dir_agent)
print("Exists:", save_dir_agent.exists())

Saved Qwen ECG tool-agent LoRA adapter to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_tool_agent_lora_1000_final
Exists: True

In [ ]:
import torch

test_example = eval_agent[0]

messages = [
    {
        "role": "system",
        "content": "You are an ECG agent that integrates outputs from specialized ECG tools and provides cautious structured explanations."
    },
    {
        "role": "user",
        "content": test_example["prompt"]
    }
]

input_text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(input_text, return_tensors="pt").to(model_agent_lora.device)

with torch.no_grad():
    generated_ids = model_agent_lora.generate(
        **inputs,
        max_new_tokens=350,
        do_sample=False
    )

generated_text = tokenizer.decode(
    generated_ids[0][inputs["input_ids"].shape[1]:],
    skip_special_tokens=True
)

print("True target response:\n")
print(test_example["response"])

print("\nQwen agent output:\n")
print(generated_text)

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

True target response:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- NORM (normal ECG): 0.003
- HYP (hypertrophy): 0.002

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

Qwen agent output:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- HYP (hypertrophy): 0.002
- NORM (normal ECG): 0.003

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
agent_eval_outputs = []

for i in range(min(10, len(eval_agent))):
    test_example = eval_agent[i]

    messages = [
        {
            "role": "system",
            "content": "You are an ECG agent that integrates outputs from specialized ECG tools and provides cautious structured explanations."
        },
        {
            "role": "user",
            "content": test_example["prompt"]
        }
    ]

    input_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(input_text, return_tensors="pt").to(model_agent_lora.device)

    with torch.no_grad():
        generated_ids = model_agent_lora.generate(
            **inputs,
            max_new_tokens=350,
            do_sample=False
        )

    generated_text = tokenizer.decode(
        generated_ids[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    agent_eval_outputs.append({
        "ecg_id": test_example["ecg_id"],
        "prompt": test_example["prompt"],
        "target_response": test_example["response"],
        "qwen_agent_output": generated_text
    })

agent_eval_outputs_df = pd.DataFrame(agent_eval_outputs)

agent_eval_outputs_path = RESULTS_DIR / "qwen_ecg_tool_agent_eval_outputs_10.csv"
agent_eval_outputs_df.to_csv(agent_eval_outputs_path, index=False)

display(agent_eval_outputs_df[["ecg_id", "target_response", "qwen_agent_output"]])
print("Saved Qwen agent eval outputs to:", agent_eval_outputs_path)

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:468: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

,ecg_id,target_response,qwen_agent_output
0,8609,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
1,20699,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
2,7600,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
3,9812,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
4,21188,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
5,17369,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
6,4362,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
7,3184,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
8,8856,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
9,12314,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...

Saved Qwen agent eval outputs to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_tool_agent_eval_outputs_10.csv

In [ ]:
import pandas as pd

In [ ]:
agent_eval_outputs_df = pd.DataFrame(agent_eval_outputs)

agent_eval_outputs_path = RESULTS_DIR / "qwen_ecg_tool_agent_eval_outputs_10.csv"
agent_eval_outputs_df.to_csv(agent_eval_outputs_path, index=False)

display(agent_eval_outputs_df[["ecg_id", "target_response", "qwen_agent_output"]])
print("Saved Qwen agent eval outputs to:", agent_eval_outputs_path)

,ecg_id,target_response,qwen_agent_output
0,8609,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
1,20699,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
2,7600,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
3,9812,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
4,21188,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
5,17369,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
6,4362,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
7,3184,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
8,8856,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
9,12314,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...

Saved Qwen agent eval outputs to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_tool_agent_eval_outputs_10.csv

In [ ]:
display(agent_eval_outputs_df[["ecg_id", "target_response", "qwen_agent_output"]])

,ecg_id,target_response,qwen_agent_output
0,8609,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
1,20699,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
2,7600,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
3,9812,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
4,21188,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
5,17369,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
6,4362,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
7,3184,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
8,8856,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...
9,12314,ECG Agent Summary\n\n1. Rhythm assessment\n- L...,ECG Agent Summary\n\n1. Rhythm assessment\n- L...

In [ ]:
i = 0

print("ECG ID:", agent_eval_outputs_df.loc[i, "ecg_id"])

print("\nTARGET RESPONSE:\n")
print(agent_eval_outputs_df.loc[i, "target_response"])

print("\nQWEN AGENT OUTPUT:\n")
print(agent_eval_outputs_df.loc[i, "qwen_agent_output"])

ECG ID: 8609

TARGET RESPONSE:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- NORM (normal ECG): 0.003
- HYP (hypertrophy): 0.002

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

QWEN AGENT OUTPUT:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- HYP (hypertrophy): 0.002
- NORM (normal ECG): 0.003

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
for i in range(3):
    print("=" * 100)
    print("ECG ID:", agent_eval_outputs_df.loc[i, "ecg_id"])

    print("\nTARGET RESPONSE:\n")
    print(agent_eval_outputs_df.loc[i, "target_response"])

    print("\nQWEN AGENT OUTPUT:\n")
    print(agent_eval_outputs_df.loc[i, "qwen_agent_output"])
    print("\n")

====================================================================================================
ECG ID: 8609

TARGET RESPONSE:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- NORM (normal ECG): 0.003
- HYP (hypertrophy): 0.002

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

QWEN AGENT OUTPUT:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 15
- Estimated heart rate: 91.6 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI, STTC
- Highest probability class: MI (myocardial infarction), probability 0.887

Class probabilities:
- MI (myocardial infarction): 0.887
- STTC (ST/T changes): 0.560
- CD (conduction disturbance): 0.152
- HYP (hypertrophy): 0.002
- NORM (normal ECG): 0.003

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction), STTC (ST/T changes).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.


====================================================================================================
ECG ID: 20699

TARGET RESPONSE:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 9
- Estimated heart rate: 61.2 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI
- Highest probability class: MI (myocardial infarction), probability 0.997

Class probabilities:
- MI (myocardial infarction): 0.997
- STTC (ST/T changes): 0.310
- HYP (hypertrophy): 0.083
- CD (conduction disturbance): 0.008
- NORM (normal ECG): 0.000

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

QWEN AGENT OUTPUT:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 9
- Estimated heart rate: 61.2 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI
- Highest probability class: MI (myocardial infarction), probability 0.997

Class probabilities:
- MI (myocardial infarction): 0.997
- STTC (ST/T changes): 0.309
- CD (conduction disturbance): 0.008
- HYP (hypertrophy): 0.083
- NORM (normal ECG): 0.000

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.


====================================================================================================
ECG ID: 7600

TARGET RESPONSE:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 12
- Estimated heart rate: 71.0 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI
- Highest probability class: MI (myocardial infarction), probability 0.987

Class probabilities:
- MI (myocardial infarction): 0.987
- NORM (normal ECG): 0.017
- CD (conduction disturbance): 0.005
- STTC (ST/T changes): 0.003
- HYP (hypertrophy): 0.001

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

QWEN AGENT OUTPUT:

ECG Agent Summary

1. Rhythm assessment
- Lead used: II
- Number of detected R-peaks: 12
- Estimated heart rate: 70.9 bpm
- Rhythm regularity: likely regular
- Scope: rhythm feature extraction only; not full arrhythmia diagnosis.

2. Diagnostic superclass classification
- Predicted label(s) above threshold: MI
- Highest probability class: MI (myocardial infarction), probability 0.987

Class probabilities:
- MI (myocardial infarction): 0.987
- STTC (ST/T changes): 0.003
- CD (conduction disturbance): 0.005
- HYP (hypertrophy): 0.001
- NORM (normal ECG): 0.017

3. Integrated interpretation
- The pretrained signal classifier suggests abnormal PTB-XL superclass label(s): MI (myocardial infarction).
- The rhythm feature tool provides supportive rhythm information based on R-peak detection.
- This is a research prototype and not a clinical diagnosis.

In [ ]:
agent_training_report = "\n".join([
    "# Qwen ECG Tool-Agent Fine-Tuning",
    "",
    "A tool-augmented ECG agent was implemented using specialized ECG tools and a supervised Qwen explanation model.",
    "",
    "## Tools",
    "",
    "1. NeuroKit2 rhythm feature tool",
    "- Input: PTB-XL raw ECG signal",
    "- Output: estimated heart rate, number of detected R-peaks, RR regularity",
    "- Scope: rhythm feature extraction only, not full arrhythmia diagnosis",
    "",
    "2. Pretrained PTB-XL signal classifier",
    "- Input: PTB-XL raw ECG signal",
    "- Output: probabilities for NORM, MI, STTC, CD, and HYP",
    "- Role: diagnostic superclass prediction",
    "",
    "3. Qwen ECG agent",
    "- Base model: Qwen/Qwen2.5-0.5B-Instruct",
    "- Fine-tuning method: LoRA",
    "- Input: structured tool outputs",
    "- Output: cautious structured ECG explanation",
    "",
    "## Training",
    "",
    "- Training examples: 1000 ECG tool-output examples",
    "- Train/evaluation split: 90/10",
    "- Epochs: 2",
    "- Final training loss: 0.5204",
    "- Validation loss after epoch 2: 0.3941",
    "",
    "## Qualitative Evaluation Example",
    "",
    "For ECG ID 8609, the Qwen agent correctly reproduced the rhythm features, PTB-XL classifier outputs, predicted labels, label explanations, and a cautious integrated interpretation.",
    "",
    "## Interpretation",
    "",
    "This agent follows a MedRAX-inspired architecture: specialized ECG tools perform signal analysis, while Qwen acts as an integration and explanation layer.",
    "Qwen is not used as the primary pathology detector. Instead, it translates rhythm features and PTB-XL classifier outputs into a structured, cautious explanation.",
    "",
    "## Limitations",
    "",
    "- The rhythm tool provides feature extraction, not full arrhythmia diagnosis.",
    "- The pretrained PTB-XL classifier is an external expert model and should be evaluated separately.",
    "- The system is a research prototype and not a clinical diagnostic tool.",
])

agent_training_report_path = RESULTS_DIR / "qwen_ecg_tool_agent_training_report.md"
agent_training_report_path.write_text(agent_training_report)

print("Saved agent training report to:", agent_training_report_path)
print("Exists:", agent_training_report_path.exists())

Saved agent training report to: /content/drive/MyDrive/ecg-qwen-modality-expert/results/qwen_ecg_tool_agent_training_report.md
Exists: True

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tqdm import tqdm

N_EVAL_CLASSIFIER = min(1000, len(df_agent))

ptbxl_eval_rows = []

for i in tqdm(range(N_EVAL_CLASSIFIER)):
    row = df_agent.iloc[i]
    record_path = PTBXL_DIR / row["filename_lr"]

    try:
        output = run_ptbxl_classifier_tool(record_path)
        probs = output["probabilities"]

        top_class = output["top_class"]
        predicted_labels = output.get("predicted_labels", [])

        true_main = row["diagnostic_class_main"]

        # Binary label aus true_main
        true_binary = "normal" if true_main == "NORM" else "pathological"

        # Binary prediction:
        # normal nur wenn ausschließlich NORM vorhergesagt wird oder Top class NORM ist
        if top_class == "NORM":
            pred_binary = "normal"
        else:
            pred_binary = "pathological"

        ptbxl_eval_rows.append({
            "ecg_id": int(row["ecg_id"]),
            "true_main": true_main,
            "top_class": top_class,
            "true_binary": true_binary,
            "pred_binary": pred_binary,
            "predicted_labels": ", ".join(predicted_labels),
            "prob_NORM": probs.get("NORM", np.nan),
            "prob_MI": probs.get("MI", np.nan),
            "prob_STTC": probs.get("STTC", np.nan),
            "prob_CD": probs.get("CD", np.nan),
            "prob_HYP": probs.get("HYP", np.nan),
        })

    except Exception as e:
        print("Failed ECG ID:", row.get("ecg_id", "unknown"), "Error:", e)

ptbxl_eval_df = pd.DataFrame(ptbxl_eval_rows)

display(ptbxl_eval_df.head())
print("Evaluated examples:", len(ptbxl_eval_df))
print("True main distribution:")
print(ptbxl_eval_df["true_main"].value_counts())
print("\nPredicted top class distribution:")
print(ptbxl_eval_df["top_class"].value_counts())

NameError: name 'df_agent' is not defined

In [ ]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
PTBXL_DIR = DATA_DIR / "ptbxl_mini"

candidate_paths = [
    RESULTS_DIR / "ecg_qa_training_table_2500_with_images.csv",
    RESULTS_DIR / "ecg_qa_training_table_1000_with_images.csv",
    RESULTS_DIR / "mini_ecg_qa_training_table_with_images.csv",
]

existing_candidates = [p for p in candidate_paths if p.exists()]

if len(existing_candidates) == 0:
    print("No standard file found. Searching MyDrive...")
    found = list(Path("/content/drive/MyDrive").rglob("*training_table*with_images*.csv"))
    for p in found:
        print(p)

    if len(found) == 0:
        raise FileNotFoundError("No ECG training table found in MyDrive.")

    csv_path = found[0]
else:
    csv_path = existing_candidates[0]

df_agent = pd.read_csv(csv_path)

print("Using CSV:", csv_path)
print("df_agent shape:", df_agent.shape)
print("Columns:", df_agent.columns.tolist())
display(df_agent.head())

Using CSV: /content/drive/MyDrive/ecg-qwen-modality-expert/results/ecg_qa_training_table_2500_with_images.csv
df_agent shape: (2500, 7)
Columns: ['ecg_id', 'filename_lr', 'diagnostic_classes', 'diagnostic_class_main', 'question', 'answer', 'image_path']

,ecg_id,filename_lr,diagnostic_classes,diagnostic_class_main,question,answer,image_path
0,5726,records100/05000/05726_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
1,19957,records100/19000/19957_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
2,12451,records100/12000/12451_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
3,12707,records100/12000/12707_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...
4,13364,records100/13000/13364_lr,['NORM'],NORM,Is this ECG normal or abnormal?,This ECG is most consistent with a normal ECG.,/content/drive/MyDrive/ecg-qwen-modality-exper...

In [ ]:
import wfdb

example_row = df_agent.iloc[0]
record_path = PTBXL_DIR / example_row["filename_lr"]

print("Record path:", record_path)
print("Header exists:", Path(str(record_path) + ".hea").exists())
print("Data exists:", Path(str(record_path) + ".dat").exists())

signal, fields = wfdb.rdsamp(str(record_path))
print("Signal shape:", signal.shape)
print("Sampling frequency:", fields["fs"])
print("Lead names:", fields["sig_name"])

ModuleNotFoundError: No module named 'wfdb'

In [ ]:
!pip install -q wfdb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.9/163.9 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 70.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
db-dtypes 1.6.0 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.3 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.3 which is incompatible.

In [ ]:
import wfdb

example_row = df_agent.iloc[0]
record_path = PTBXL_DIR / example_row["filename_lr"]

print("Record path:", record_path)
print("Header exists:", Path(str(record_path) + ".hea").exists())
print("Data exists:", Path(str(record_path) + ".dat").exists())

signal, fields = wfdb.rdsamp(str(record_path))
print("Signal shape:", signal.shape)
print("Sampling frequency:", fields["fs"])
print("Lead names:", fields["sig_name"])

Record path: /content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/records100/05000/05726_lr
Header exists: True
Data exists: True
Signal shape: (1000, 12)
Sampling frequency: 100
Lead names: ['I', 'II', 'III', 'AVR', 'AVL', 'AVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']

In [ ]:
print("ptbxl_model exists:", "ptbxl_model" in globals())
print("run_ptbxl_classifier_tool exists:", "run_ptbxl_classifier_tool" in globals())
print("df_agent exists:", "df_agent" in globals())

ptbxl_model exists: False
run_ptbxl_classifier_tool exists: False
df_agent exists: True

In [ ]:
!pip install -q huggingface_hub tensorflow keras wfdb

In [ ]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

import json
import numpy as np
import pandas as pd
import wfdb
import keras
from pathlib import Path
from huggingface_hub import hf_hub_download

PROJECT_DIR = Path("/content/drive/MyDrive/ecg-qwen-modality-expert")
DATA_DIR = PROJECT_DIR / "data"
RESULTS_DIR = PROJECT_DIR / "results"
PTBXL_DIR = DATA_DIR / "ptbxl_mini"

# Falls df_agent nicht mehr existiert, neu laden
if "df_agent" not in globals():
    candidate_paths = [
        RESULTS_DIR / "ecg_qa_training_table_2500_with_images.csv",
        RESULTS_DIR / "ecg_qa_training_table_1000_with_images.csv",
        RESULTS_DIR / "mini_ecg_qa_training_table_with_images.csv",
    ]

    existing_candidates = [p for p in candidate_paths if p.exists()]

    if len(existing_candidates) == 0:
        found = list(Path("/content/drive/MyDrive").rglob("*training_table*with_images*.csv"))
        if len(found) == 0:
            raise FileNotFoundError("No ECG training table found.")
        csv_path = found[0]
    else:
        csv_path = existing_candidates[0]

    df_agent = pd.read_csv(csv_path)
    print("Loaded df_agent from:", csv_path)

print("df_agent shape:", df_agent.shape)

# Externes Modell von Hugging Face laden
repo_id = "Steenslid/ecg-ptbxl-classification"

model_path = hf_hub_download(
    repo_id=repo_id,
    filename="ecg_model.keras"
)

norm_path = hf_hub_download(
    repo_id=repo_id,
    filename="normalisation_params.npz"
)

thresholds_path = hf_hub_download(
    repo_id=repo_id,
    filename="thresholds.json"
)

ptbxl_model = keras.saving.load_model(model_path)
normalisation_params = np.load(norm_path)

with open(thresholds_path, "r") as f:
    thresholds = json.load(f)

print("Loaded pretrained PTB-XL classifier.")
print("Model input shape:", ptbxl_model.input_shape)
print("Model output shape:", ptbxl_model.output_shape)
print("Normalisation keys:", normalisation_params.files)
print("Thresholds:", thresholds)


def normalize_ecg_signal(x, normalisation_params):
    """
    x expected shape: 1000 x 12
    returns: 1000 x 12
    """
    keys = normalisation_params.files

    if "mean" in keys and "std" in keys:
        mean = normalisation_params["mean"]
        std = normalisation_params["std"]
    elif "means" in keys and "stds" in keys:
        mean = normalisation_params["means"]
        std = normalisation_params["stds"]
    elif "mu" in keys and "sigma" in keys:
        mean = normalisation_params["mu"]
        std = normalisation_params["sigma"]
    else:
        print("Warning: Unknown normalisation keys. Returning unnormalized signal.")
        return x.astype("float32")

    mean = np.squeeze(mean)
    std = np.squeeze(std)

    x_norm = (x - mean) / (std + 1e-8)
    x_norm = np.squeeze(x_norm)

    return x_norm.astype("float32")


def run_ptbxl_classifier_tool(record_path):
    signal, fields = wfdb.rdsamp(str(record_path))

    x = signal.astype("float32")

    # Erwartet: 1000 x 12
    if x.shape[0] != 1000:
        if x.shape[0] > 1000:
            x = x[:1000, :]
        else:
            pad_len = 1000 - x.shape[0]
            x = np.pad(x, ((0, pad_len), (0, 0)), mode="constant")

    if x.shape[1] != 12:
        raise ValueError(f"Expected 12 leads, but got shape {x.shape}")

    x = normalize_ecg_signal(x, normalisation_params)

    # Modell erwartet: batch x 1000 x 12
    x_batch = np.expand_dims(x, axis=0)

    y_pred = ptbxl_model.predict(x_batch, verbose=0)

    if isinstance(y_pred, list):
        y_pred = y_pred[0]

    probs = np.array(y_pred).reshape(-1)

    labels = ["NORM", "MI", "STTC", "CD", "HYP"]

    if isinstance(thresholds, dict):
        predicted_labels = [
            label for label, prob in zip(labels, probs)
            if prob >= float(thresholds.get(label, 0.5))
        ]
    else:
        predicted_labels = [
            label for label, prob, thr in zip(labels, probs, thresholds)
            if prob >= float(thr)
        ]

    if len(predicted_labels) == 0:
        predicted_labels = [labels[int(np.argmax(probs))]]

    return {
        "tool_name": "pretrained PTB-XL classifier",
        "classes": labels,
        "probabilities": {label: float(prob) for label, prob in zip(labels, probs)},
        "predicted_labels": predicted_labels,
        "top_class": labels[int(np.argmax(probs))],
        "interpretation_scope": "Pretrained signal-based PTB-XL superclass classifier."
    }

print("run_ptbxl_classifier_tool is ready.")

df_agent shape: (2500, 7)

ecg_model.keras:   0%|          | 0.00/8.43M [00:00<?, ?B/s]

normalisation_params.npz:   0%|          | 0.00/596 [00:00<?, ?B/s]

thresholds.json:   0%|          | 0.00/121 [00:00<?, ?B/s]

Loaded pretrained PTB-XL classifier.
Model input shape: (None, 1000, 12)
Model output shape: (None, 5)
Normalisation keys: ['mean', 'std']
Thresholds: {'NORM': 0.44000000000000006, 'MI': 0.35000000000000003, 'STTC': 0.33, 'CD': 0.26000000000000006, 'HYP': 0.2}
run_ptbxl_classifier_tool is ready.

In [ ]:
example_row = df_agent.iloc[0]
record_path = PTBXL_DIR / example_row["filename_lr"]

print("Record path:", record_path)
print("Header exists:", Path(str(record_path) + ".hea").exists())
print("Data exists:", Path(str(record_path) + ".dat").exists())

ptbxl_output = run_ptbxl_classifier_tool(record_path)
ptbxl_output

Record path: /content/drive/MyDrive/ecg-qwen-modality-expert/data/ptbxl_mini/records100/05000/05726_lr
Header exists: True
Data exists: True

{'tool_name': 'pretrained PTB-XL classifier',
 'classes': ['NORM', 'MI', 'STTC', 'CD', 'HYP'],
 'probabilities': {'NORM': 0.9920564293861389,
  'MI': 0.0007271060021594167,
  'STTC': 0.0014195592375472188,
  'CD': 0.0031786104664206505,
  'HYP': 0.0004819866153411567},
 'predicted_labels': ['NORM'],
 'top_class': 'NORM',
 'interpretation_scope': 'Pretrained signal-based PTB-XL superclass classifier.'}

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tqdm import tqdm

N_EVAL_CLASSIFIER = min(1000, len(df_agent))

ptbxl_eval_rows = []

for i in tqdm(range(N_EVAL_CLASSIFIER)):
    row = df_agent.iloc[i]
    record_path = PTBXL_DIR / row["filename_lr"]

    try:
        output = run_ptbxl_classifier_tool(record_path)
        probs = output["probabilities"]

        top_class = output["top_class"]
        predicted_labels = output.get("predicted_labels", [])

        true_main = row["diagnostic_class_main"]

        true_binary = "normal" if true_main == "NORM" else "pathological"
        pred_binary = "normal" if top_class == "NORM" else "pathological"

        ptbxl_eval_rows.append({
            "ecg_id": int(row["ecg_id"]),
            "true_main": true_main,
            "top_class": top_class,
            "true_binary": true_binary,
            "pred_binary": pred_binary,
            "predicted_labels": ", ".join(predicted_labels),
            "prob_NORM": probs.get("NORM", np.nan),
            "prob_MI": probs.get("MI", np.nan),
            "prob_STTC": probs.get("STTC", np.nan),
            "prob_CD": probs.get("CD", np.nan),
            "prob_HYP": probs.get("HYP", np.nan),
        })

    except Exception as e:
        print("Failed ECG ID:", row.get("ecg_id", "unknown"), "Error:", e)

ptbxl_eval_df = pd.DataFrame(ptbxl_eval_rows)

display(ptbxl_eval_df.head())
print("Evaluated examples:", len(ptbxl_eval_df))
print("\nTrue main distribution:")
print(ptbxl_eval_df["true_main"].value_counts())
print("\nPredicted top class distribution:")
print(ptbxl_eval_df["top_class"].value_counts())

100%|██████████| 1000/1000 [12:34<00:00,  1.33it/s]

,ecg_id,true_main,top_class,true_binary,pred_binary,predicted_labels,prob_NORM,prob_MI,prob_STTC,prob_CD,prob_HYP
0,5726,NORM,NORM,normal,normal,NORM,0.992056,0.000727,0.001420,0.003179,0.000482
1,19957,NORM,NORM,normal,normal,NORM,0.944263,0.011218,0.011116,0.029648,0.003430
2,12451,NORM,NORM,normal,normal,NORM,0.974085,0.006688,0.010100,0.001923,0.000437
3,12707,NORM,HYP,normal,pathological,"NORM, HYP",0.530303,0.003572,0.012525,0.005492,0.640135
4,13364,NORM,NORM,normal,normal,NORM,0.946550,0.027738,0.005418,0.023868,0.000333

Evaluated examples: 1000

True main distribution:
true_main
NORM    500
MI      500
Name: count, dtype: int64

Predicted top class distribution:
top_class
NORM    517
MI      400
STTC     64
CD       10
HYP       9
Name: count, dtype: int64